// 단어별 발음 기호와 뜻. index.html이 채점 결과에서 씁니다.
//
// ipa  발음 기호. 사전 API(dictionaryapi.dev)에서 받아 왔습니다.
//      사전에 없는 단어는 이 항목이 없고, 그 자리는 비워서 보여줍니다.
// ko   한국어 뜻. 기능어(the, to, you 등)에는 달지 않았습니다.
//
// pron 한글 발음. 규칙으로는 맞출 수 없는 말에만 적습니다.
//      대괄호는 강세 자리입니다. 예: "[모]델"
//      영어 소리와 우리말 표기가 어긋나는 경우가 있습니다.
//        · job은 표기법대로면 '조브'지만 실제로는 '잡'으로 씁니다
//        · model과 little은 소리가 같은 꼴인데 '모델'과 '리틀'로 갈립니다
//        · coffee의 '커피'는 오래된 차용어라 발음에서 나오지 않습니다
//      이런 말만 적고, 나머지는 아래 변환기에 맡깁니다.
//
// 한글 발음은 pron이 없으면 index.html의 변환기가 ipa로 그때그때 만듭니다.

const WORDS = {
  "a": {ipa:"ə"},
  "aback": {ipa:"əˈbæk",ko:"깜짝 놀라"},
  "about": {ipa:"əˈbaʊt"},
  "abroad": {ipa:"əˈbɹɔːd",ko:"외국으로"},
  "absurd": {ipa:"əbˈsɜːd",ko:"터무니없는"},
  "accept": {ipa:"ækˈsɛpt",ko:"받아들이다"},
  "access": {ipa:"ˈæksɛs",ko:"이용 권한"},
  "account": {ipa:"ə.ˈkaʊnt",ko:"계정"},
  "across": {ipa:"əˈkɹɑs",ko:"가로질러",pron:"어크[로]스"},
  "adapter": {ipa:"əˈdæptə",ko:"어댑터"},
  "adaptor": {ipa:"əˈdæptə",ko:"어댑터"},
  "add": {ipa:"æd",ko:"더하다"},
  "additional": {ipa:"əˈdɪʃənəl",ko:"추가의"},
  "address": {ipa:"æˈdɹɛs",ko:"주소",pron:"어[드레]스"},
  "adorable": {ipa:"əˈdɔːɹəbəl",ko:"사랑스러운"},
  "adults": {ipa:"ˈædʌlts",ko:"성인들"},
  "advance": {ipa:"ədˈvaːns",ko:"미리",pron:"어드[밴]스"},
  "advice": {ipa:"ədˈvaɪs",ko:"조언"},
  "afraid": {ipa:"əˈfɹeɪd",ko:"두려운, 유감스러운"},
  "after": {ipa:"ˈɑːftə",ko:"~을 닮아 (take after)"},
  "again": {ipa:"əˈɡeɪn"},
  "against": {ipa:"əˈɡeɪnst",ko:"반대하여"},
  "age": {ipa:"eɪdʒ",ko:"나이"},
  "ages": {ipa:"ˈeɪ.dʒɪz",ko:"오랜 시간"},
  "agree": {ipa:"əˈɡɹi",ko:"동의하다"},
  "ahead": {ipa:"əˈhɛd",ko:"앞으로"},
  "air": {ipa:"ˈɛə",ko:"공기"},
  "airflow": {ipa:"ˈeəfləʊ",ko:"공기 흐름"},
  "airplane": {ipa:"ˈɛəpleɪn",ko:"비행기"},
  "airport": {ipa:"ˈɛə.pɔːt",ko:"공항"},
  "airsick": {ipa:"ˈeəsɪk",ko:"비행기 멀미가 나는"},
  "aisle": {ipa:"aɪl",ko:"통로"},
  "alike": {ipa:"əˈlaɪk",ko:"서로 닮은"},
  "all": {ipa:"ɔːl"},
  "allergic": {ipa:"əˈlɜːdʒɪk",ko:"알레르기가 있는"},
  "allowance": {ipa:"əˈlaʊəns",ko:"허용량"},
  "allowed": {ipa:"əˈlaʊd",ko:"허용된"},
  "almost": {ipa:"ɔːl.ˈməʊst",ko:"거의"},
  "alone": {ipa:"əˈləʊn",ko:"혼자"},
  "along": {ipa:"əˈlɒŋ",ko:"잘 지내는 (get along)"},
  "already": {ipa:"ɔːlˈɹedi"},
  "alright": {ipa:"ɒˈɹaɪt",ko:"괜찮은",pron:"올[라]이트"},
  "always": {ipa:"ˈɔːlweɪz",ko:"늘, 언제나"},
  "am": {ipa:"æm"},
  "amazing": {ipa:"əˈmeɪzɪŋ",ko:"놀라운"},
  "an": {ipa:"æn"},
  "and": {ipa:"ænd"},
  "angle": {ipa:"ˈæŋɡəl",ko:"각도, 관점"},
  "announcement": {ipa:"əˈnaʊnsmənt",ko:"안내 방송"},
  "annoying": {ipa:"əˈnɔɪɪŋ",ko:"짜증나는"},
  "another": {ipa:"əˈnʌðə"},
  "answer": {ipa:"ˈɑːnsə",ko:"답하다",pron:"[앤]서"},
  "anxious": {ipa:"ˈaŋ(k)ʃəs",ko:"불안한",pron:"[앵]셔스"},
  "any": {ipa:"ˈæni"},
  "anybody": {ipa:"ˈenibɒdi"},
  "anymore": {ipa:"ˌæ.niˈmoːɹ",ko:"더 이상"},
  "anyone": {ipa:"ˈæniˌwʌn"},
  "anything": {ipa:"ˈɛ.nə.θɪŋ",ko:"무엇이든"},
  "anytime": {ipa:"ˈeniˌtaɪm",ko:"언제든"},
  "anywhere": {ipa:"ˈɛn.iː.(h)wɛə(ɹ)",ko:"어디든"},
  "apart": {ipa:"əˈpɑː(ɹ)t",ko:"떨어져"},
  "apologised": {ipa:"əˈpɒlədʒaɪzd",ko:"사과했다"},
  "apologized": {ipa:"əˈpɒlədʒaɪzd",ko:"사과했다"},
  "apology": {ipa:"əˈpɒl.ə.dʒi",ko:"사과"},
  "app": {ipa:"[ʔæʔp̚]",ko:"앱"},
  "appreciate": {ipa:"əˈpɹiː.si.eɪt",ko:"고맙게 여기다"},
  "approved": {ipa:"əˈpɹuːvd",ko:"승인된"},
  "are": {ipa:"ɑː"},
  "area": {ipa:"ˈeəɹɪə",ko:"지역"},
  "aren't": {ipa:"ɑːnt"},
  "arms": {ipa:"ɑːmz",ko:"팔"},
  "around": {ipa:"əˈɹaʊnd",ko:"주변에, 즈음"},
  "arrange": {ipa:"əˈɹeɪndʒ",ko:"마련하다"},
  "arrival": {ipa:"əˈɹaɪ.vəl",ko:"도착"},
  "arrived": {ipa:"əˈɹaɪvd",ko:"도착했다"},
  "as": {ipa:"æz"},
  "aside": {ipa:"əˈsaɪd",ko:"옆으로"},
  "ask": {ipa:"ɑːsk",ko:"묻다, 부탁하다",pron:"[애]스크"},
  "asked": {ipa:"ɑːskt",ko:"물었다",pron:"[애]스크트"},
  "asking": {ipa:"ˈɑːskɪŋ",ko:"묻는 것",pron:"[애]스킹"},
  "assigned": {ipa:"əˈsaɪnd",ko:"정해진"},
  "assist": {ipa:"əˈsɪst",ko:"돕다"},
  "assistance": {ipa:"əˈsɪs.təns",ko:"도움"},
  "at": {ipa:"æt"},
  "attending": {ipa:"əˈtɛndɪŋ",ko:"참석하는"},
  "attention": {ipa:"əˈtenʃən",ko:"관심, 보살핌"},
  "authentic": {ipa:"ɒ.ˈθɛn.tɪk",ko:"진짜의",pron:"어[쎈]틱"},
  "authorisation": {ipa:"ˌɔːθəɹaɪˈzeɪʃən",ko:"허가"},
  "authorization": {ipa:"ˌɔːθəɹaɪˈzeɪʃən",ko:"허가"},
  "automatically": {ipa:"ˈɔːtəʊˌmæt.ɪk(.ə)li",ko:"자동으로"},
  "available": {ipa:"əˈveɪləb(ə)l",ko:"이용 가능한"},
  "away": {ipa:"əˈweɪ"},
  "awful": {ipa:"ˈɔːfəl",ko:"끔찍한"},
  "awkward": {ipa:"ˈɔːkwəd",ko:"어색한",pron:"[오]크워드"},
  "baby": {ipa:"ˈbeɪbi",ko:"아기"},
  "back": {ipa:"bæk"},
  "background": {ipa:"ˈbæk.ɡɹaʊnd",ko:"배경"},
  "bad": {ipa:"bæd",ko:"나쁜"},
  "bag": {ipa:"bæɡ",ko:"가방, 봉투",pron:"[백]"},
  "baggage": {ipa:"ˈbæɡɪdʒ",ko:"수하물"},
  "bags": {ipa:"bæɡz",ko:"짐",pron:"[백]스"},
  "bathroom": {ipa:"ˈbɑːθruːm",ko:"화장실",pron:"[배]쓰룸"},
  "batteries": {ipa:"ˈbæt(ə)ɹiz",ko:"건전지"},
  "be": {ipa:"biː"},
  "bear": {ipa:"bɛə(ɹ)",ko:"참다, 견디다"},
  "beautiful": {ipa:"ˈbjuːtɪfəl",ko:"아름다운"},
  "bed": {ipa:"bed",ko:"침대"},
  "bedding": {ipa:"ˈbɛdɪŋ",ko:"침구"},
  "beds": {ipa:"bɛdz",ko:"침대"},
  "been": {ipa:"biːn"},
  "beer": {ipa:"bɪə",ko:"맥주"},
  "before": {ipa:"bɪˈfɔː"},
  "begin": {ipa:"biˈɡɪn",ko:"시작하다"},
  "begun": {ipa:"bɪˈɡʌn",ko:"시작된"},
  "behind": {ipa:"bəˈhaɪnd",ko:"뒤에"},
  "being": {ipa:"ˈbiːɪŋ"},
  "believe": {ipa:"bɪˈliːv",ko:"믿다"},
  "bell": {ipa:"bel",ko:"벨"},
  "belt": {ipa:"bɛlt",ko:"벨트"},
  "benefits": {ipa:"ˈbenɪfɪts",ko:"이점"},
  "beside": {ipa:"bɪˈsaɪd"},
  "best": {ipa:"ˈbɛst",ko:"최고의"},
  "better": {ipa:"ˈbetə",ko:"더 좋은"},
  "between": {ipa:"bɪˈtwiːn"},
  "beverages": {ipa:"ˈbevəɹɪdʒɪz",ko:"음료"},
  "big": {ipa:"bɪɡ",ko:"큰",pron:"[빅]"},
  "bigger": {ipa:"ˈbɪɡə",ko:"더 큰"},
  "bike": {ipa:"baɪk",ko:"자전거"},
  "bill": {ipa:"bɪl",ko:"청구서, 계산서"},
  "bin": {ipa:"bɪn",ko:"짐칸, 통"},
  "birthday": {ipa:"ˈbɜːθ.deɪ",ko:"생일"},
  "bit": {ipa:"bɪt",ko:"조금",pron:"[비]트"},
  "bite": {ipa:"baɪt",ko:"한 입"},
  "blame": {ipa:"bleɪm",ko:"탓하다"},
  "blanket": {ipa:"ˈblæŋkɪt",ko:"담요"},
  "blocked": {ipa:"blɒkt",ko:"막힌"},
  "blocks": {ipa:"blɒks",ko:"블록, 구역"},
  "board": {ipa:"bɔːd",ko:"탑승하다"},
  "boarding": {ipa:"ˈbɔːdɪŋ",ko:"탑승"},
  "book": {ipa:"buːk",ko:"예약하다",pron:"[북]"},
  "booked": {ipa:"bʊkt",ko:"예약된"},
  "booking": {ipa:"ˈbuːkɪŋ",ko:"예약"},
  "boot": {ipa:"buːt",ko:"트렁크"},
  "boring": {ipa:"ˈbɔːɹɪŋ",ko:"지루한"},
  "borrow": {ipa:"ˈbɒɹəʊ",ko:"빌리다"},
  "boss": {ipa:"bɒs",ko:"상사"},
  "both": {ipa:"bəʊθ"},
  "bother": {ipa:"ˈbɒðə",ko:"귀찮게 하다"},
  "bothering": {ipa:"ˈbɒðəɹɪŋ",ko:"방해하는"},
  "bothers": {ipa:"ˈbɒðəz",ko:"거슬리게 하다"},
  "bottles": {ipa:"ˈbɒtl̩z",ko:"병"},
  "box": {ipa:"bɒks",ko:"상자",pron:"[박]스"},
  "boy": {ipa:"bɔɪ",ko:"남자아이"},
  "boys": {ipa:"bɔɪz",ko:"아들들, 남자아이들"},
  "break": {ipa:"bɹeɪk",ko:"휴식"},
  "breakable": {ipa:"ˈbɹeɪkəbl",ko:"깨지기 쉬운"},
  "breakfast": {ipa:"ˈbɹɛkfəst",ko:"아침 식사"},
  "breathe": {ipa:"bɹiːð",ko:"숨 쉬다"},
  "breather": {ipa:"ˈbɹiːðə",ko:"한숨 돌리기"},
  "bridge": {ipa:"bɹɪdʒ",ko:"다리"},
  "bright": {ipa:"bɹaɪt",ko:"밝은"},
  "bring": {ipa:"ˈbɹɪŋ",ko:"가져오다"},
  "brings": {ipa:"ˈbɹɪŋz",ko:"데려오다"},
  "broken": {ipa:"ˈbɹəʊkən",ko:"고장난"},
  "brother": {ipa:"ˈbɹʌðə",ko:"형, 오빠, 남동생"},
  "brother-in": {ipa:"ˈbɹʌðəɹɪn",ko:"인척 관계를 만드는 앞말"},
  "browsing": {ipa:"ˈbɹaʊzɪŋ",ko:"둘러보는"},
  "buckle": {ipa:"ˈbʌk(ə)l",ko:"채우다"},
  "buffet": {ipa:"ˈbʊfeɪ",ko:"뷔페",pron:"[뷔]페"},
  "bug": {ipa:"bʌɡ",ko:"벌레"},
  "bugging": {ipa:"ˈbʌɡɪŋ",ko:"성가시게 하는"},
  "building": {ipa:"ˈbɪldɪŋ",ko:"건물"},
  "burden": {ipa:"ˈbɜːdn",ko:"부담을 주다"},
  "burned": {ipa:"ˈbɜː(ɹ)nd",ko:"소진된"},
  "burning": {ipa:"ˈbɜːnɪŋ",ko:"타는"},
  "bus": {ipa:"bʌs",ko:"버스"},
  "buses": {ipa:"ˈbʌsɪz",ko:"버스들"},
  "business": {ipa:"ˈbɪznəs",ko:"일, 사업",pron:"[비]즈니스"},
  "busy": {ipa:"ˈbɪzi",ko:"바쁜"},
  "but": {ipa:"bʌt"},
  "button": {ipa:"ˈbʌtən",ko:"버튼"},
  "buy": {ipa:"baɪ",ko:"사다"},
  "by": {ipa:"baɪ"},
  "cab": {ipa:"kæb",ko:"택시",pron:"[캡]"},
  "cafe": {ipa:"ˈkæfeɪ",ko:"카페",pron:"카[페]"},
  "calendar": {ipa:"ˈkæl.ən.də",ko:"일정표",pron:"[캘]린더"},
  "call": {ipa:"kɔːɫ",ko:"부르다, 전화하다"},
  "called": {ipa:"[kɔld]",ko:"불렀다"},
  "calm": {ipa:"kɑːm",ko:"진정시키다"},
  "came": {ipa:"keɪm",ko:"왔다"},
  "camera": {ipa:"ˈkæməɹə",ko:"카메라",pron:"[카]메라"},
  "can": {ipa:"ˈkæn"},
  "can't": {ipa:"kɑːnt"},
  "cancel": {ipa:"ˈkænsl̩",ko:"취소하다",pron:"[캔]슬"},
  "canceled": {ipa:"ˈkænsəld",ko:"취소된",pron:"[캔]슬드"},
  "cancelled": {ipa:"ˈkænsəld",ko:"취소된",pron:"[캔]슬드"},
  "cannot": {ipa:"kəˈnɑt",ko:"할 수 없다"},
  "cap": {ipa:"kæp",ko:"모자"},
  "card": {ipa:"kɑːd",ko:"카드"},
  "cards": {ipa:"kɑːdz",ko:"카드"},
  "care": {ipa:"kɛə",ko:"돌봄, 신경 씀"},
  "carousel": {ipa:"ˌkærəˈsɛl",ko:"수하물 벨트"},
  "carry": {ipa:"ˈkæ.ɹi",ko:"나르다"},
  "carry-on": {ipa:"ˈkæri ɒn",ko:"기내 반입용"},
  "carrying": {ipa:"ˈkæ.ɹiɪŋ",ko:"소지한"},
  "carryon": {ipa:"ˈkæri ɒn",ko:"기내 반입용"},
  "cart": {ipa:"kɑːt",ko:"수레"},
  "case": {ipa:"keɪs",ko:"경우"},
  "cash": {ipa:"kæʃ",ko:"현금"},
  "catch": {ipa:"kæt͡ʃ",ko:"잡다, 걸리다"},
  "cats": {ipa:"kæts",ko:"고양이"},
  "caught": {ipa:"[k̠ʰoːt]",ko:"잡았다"},
  "center": {ipa:"ˈsɛn.tə(ɹ)",ko:"가운데"},
  "certain": {ipa:"ˈsɜːtən",ko:"확실한"},
  "chair": {ipa:"t͡ʃɛə(ɹ)",ko:"의자"},
  "change": {ipa:"tʃeɪndʒ",ko:"바꾸다, 잔돈"},
  "changed": {ipa:"t͡ʃeɪnd͡ʒd",ko:"바뀐"},
  "changing": {ipa:"ˈtʃeɪndʒɪŋ",ko:"바꾸는"},
  "channel": {ipa:"ˈtʃænəl",ko:"채널"},
  "channels": {ipa:"ˈtʃænəlz",ko:"채널들"},
  "charge": {ipa:"t͡ʃɑːd͡ʒ",ko:"요금"},
  "charger": {ipa:"ˈtʃɑːdʒə",ko:"충전기"},
  "chat": {ipa:"tʃæt",ko:"이야기"},
  "cheaper": {ipa:"ˈtʃiːpə",ko:"더 싼"},
  "check": {ipa:"t͡ʃɛk",ko:"확인하다, 계산서",pron:"[체]크"},
  "check-in": {ipa:"ˈtʃek ɪn",ko:"체크인"},
  "check-out": {ipa:"ˈtʃek aʊt",ko:"체크아웃",pron:"[체]크아웃"},
  "checked": {ipa:"tʃɛkt",ko:"부친, 확인한",pron:"[체]크트"},
  "checkout": {ipa:"ˈtʃekaʊt",ko:"체크아웃",pron:"[체]크아웃"},
  "checkpoint": {ipa:"ˈtʃekpɔɪnt",ko:"검색대",pron:"[체]크포인트"},
  "chef": {ipa:"ʃɛf",ko:"주방장"},
  "cherish": {ipa:"ˈtʃɛɹɪʃ",ko:"소중히 여기다"},
  "chest": {ipa:"tʃest",ko:"가슴"},
  "chicken": {ipa:"ˈt͡ʃɪkɪn",ko:"닭고기"},
  "child": {ipa:"t͡ʃaɪld",ko:"아이"},
  "children": {ipa:"ˈtʃɪldɹən",ko:"아이들",pron:"[칠]드런"},
  "chilly": {ipa:"ˈtʃɪli",ko:"쌀쌀한"},
  "chin": {ipa:"tʃɪn",ko:"턱"},
  "choice": {ipa:"tʃɔɪs",ko:"선택"},
  "chopsticks": {ipa:"ˈtʃɒpstɪks",ko:"젓가락",pron:"[찹]스틱스"},
  "cilantro": {ipa:"siˈlæntɹəʊ",ko:"고수"},
  "city": {ipa:"ˈsɪti",ko:"도시"},
  "claim": {ipa:"kleɪm",ko:"찾다, 청구하다"},
  "class": {ipa:"klɑːs",ko:"반, 수업",pron:"[클래]스"},
  "clean": {ipa:"kliːn",ko:"청소하다"},
  "cleaned": {ipa:"kliːnd",ko:"청소된"},
  "clear": {ipa:"klɪə(ɹ)",ko:"치우다, 확인된"},
  "cleared": {ipa:"klɪəd",ko:"통과된"},
  "clogged": {ipa:"klɒɡd",ko:"막힌"},
  "close": {ipa:"kləʊz",ko:"닫다, 가까운"},
  "code": {ipa:"kəʊd",ko:"번호"},
  "coffee": {ipa:"ˈkɑ.fi",ko:"커피",pron:"[커]피"},
  "cold": {ipa:"kəʊld",ko:"추운, 감기"},
  "colleague": {ipa:"ˈkɒliːɡ",ko:"동료"},
  "college": {ipa:"ˈkɒlɪdʒ",ko:"대학",pron:"[칼]리지"},
  "color": {ipa:"ˈkʌl.ə(ɹ)",ko:"색"},
  "colour": {ipa:"ˈkʌlə",ko:"색"},
  "combination": {ipa:"kɒmbɪˈneɪʃən",ko:"조합 번호"},
  "come": {ipa:"kʌm",ko:"오다"},
  "comes": {ipa:"kʌmz"},
  "comfortable": {ipa:"ˈkʌm.fə.tə.bəl",ko:"편안한"},
  "coming": {ipa:"ˈkʌmɪŋ",ko:"다가오는"},
  "communal": {ipa:"kəˈmju.nəl",ko:"공용의"},
  "commute": {ipa:"kəˈmjuːt",ko:"통근"},
  "companion": {ipa:"kəmˈpænjən",ko:"동행"},
  "company": {ipa:"ˈkʌmpəni",ko:"회사"},
  "compensation": {ipa:"ˌkɒmpɛnˈseɪʃən",ko:"보상"},
  "complaint": {ipa:"kəmˈpleɪnt",ko:"불만 접수"},
  "completely": {ipa:"kəmˈpliːtli",ko:"완전히"},
  "compliment": {ipa:"ˈkɒmplɪmənt",ko:"칭찬"},
  "compliments": {ipa:"ˈkɒmplɪmənts",ko:"칭찬"},
  "conditioner": {ipa:"kənˈdɪʃənə",ko:"조절기"},
  "conference": {ipa:"ˈkɒn.fə.ɹəns",ko:"학회, 큰 회의"},
  "confirm": {ipa:"kənˈfɜːm",ko:"확인하다"},
  "confirmation": {ipa:"ˌkɒn.fəˈmeɪ.ʃən",ko:"확인"},
  "confused": {ipa:"kənˈfjuːzd",ko:"헷갈리는"},
  "confusing": {ipa:"kənˈfjuːzɪŋ",ko:"헷갈리게 하는"},
  "congratulations": {ipa:"kənˌɡɹad͡ʒəˈleɪʃ(ə)nz",ko:"축하합니다"},
  "connect": {ipa:"kəˈnɛkt",ko:"이어주다"},
  "connecting": {ipa:"kəˈnɛktɪŋ",ko:"연결되는"},
  "connection": {ipa:"kəˈnɛkʃən",ko:"연결, 환승"},
  "cons": {ipa:"kɒnz",ko:"단점"},
  "construction": {ipa:"kənˈstɹʌkʃən",ko:"공사"},
  "consulate": {ipa:"ˈkɒnsjʊlət",ko:"영사관"},
  "contact": {ipa:"ˈkɒntækt",ko:"연락"},
  "contain": {ipa:"kənˈteɪn",ko:"포함하다"},
  "control": {ipa:"kənˈtɹəʊl",ko:"관리"},
  "convenience": {ipa:"kənˈviːnɪəns",ko:"편의"},
  "convenient": {ipa:"kənˈviːniənt",ko:"편한, 알맞은"},
  "conversation": {ipa:"ˌkɒn.vəˈseɪ.ʃən",ko:"대화"},
  "converter": {ipa:"kənˈvɜːtə",ko:"변압기"},
  "convinced": {ipa:"kənˈvɪnst",ko:"확신하는"},
  "cook": {ipa:"kʊk",ko:"요리사"},
  "cooking": {ipa:"ˈkʊkɪŋ",ko:"요리"},
  "copies": {ipa:"ˈkɒpiz",ko:"부, 사본",pron:"[카]피즈"},
  "corner": {ipa:"ˈkɔːnə(ɹ)",ko:"모퉁이"},
  "correct": {ipa:"kəˈɹekt",ko:"맞는"},
  "corridor": {ipa:"ˈkɒɹɪˌdɔː(ɹ)",ko:"복도"},
  "cot": {ipa:"kɑt",ko:"아기 침대"},
  "could": {ipa:"kʊd"},
  "couldn't": {ipa:"ˈkʊdənt"},
  "count": {ipa:"kaʊnt",ko:"믿다, 세다"},
  "counter": {ipa:"ˈkaʊntə",ko:"카운터"},
  "couple": {ipa:"ˈkʌpəl",ko:"짝을 이룬 두 사람"},
  "coupon": {ipa:"ˈkuːˌpɒn",ko:"쿠폰"},
  "cousins": {ipa:"ˈkʌzənz",ko:"사촌들"},
  "cozy": {ipa:"ˈkoʊzi",ko:"아늑한"},
  "crazy": {ipa:"ˈkɹeɪzi",ko:"정신없는"},
  "crib": {ipa:"kɹɪb",ko:"아기 침대",pron:"[크립]"},
  "cross": {ipa:"kɹɑs",ko:"건너다",pron:"[크로]스"},
  "crossed": {ipa:"kɹɑst",ko:"엇갈리게 겹친",pron:"[크로]스트"},
  "crossing": {ipa:"ˈkɹɑsɪŋ",ko:"횡단보도",pron:"[크로]싱"},
  "crosswalk": {ipa:"ˈkɹɒswɔːk",ko:"횡단보도"},
  "cup": {ipa:"kʌp",ko:"컵"},
  "curfew": {ipa:"ˈkɜː.fjuː",ko:"통금"},
  "curtain": {ipa:"ˈkɜːtən",ko:"커튼"},
  "customs": {ipa:"ˈkʌstəmz",ko:"세관"},
  "cute": {ipa:"kjuːt",ko:"귀여운"},
  "cutoff": {ipa:"ˈkʌtɒf",ko:"마감"},
  "cutting": {ipa:"ˈkʌtɪŋ",ko:"끊기는"},
  "dad": {ipa:"dæd",ko:"아빠"},
  "dad's": {ipa:"dædz",ko:"아빠의"},
  "damaged": {ipa:"ˈdæmɪdʒd",ko:"파손된"},
  "damp": {ipa:"dæmp",ko:"눅눅한"},
  "date": {ipa:"deɪt",ko:"날짜"},
  "daughter": {ipa:"ˈdɔːtə",ko:"딸"},
  "daughter's": {ipa:"ˈdɔːtəz",ko:"딸의"},
  "day": {ipa:"deɪ",ko:"날"},
  "daycare": {ipa:"ˈdeɪkeə",ko:"어린이집"},
  "days": {ipa:"deɪz",ko:"날들"},
  "deactivated": {ipa:"diːˈæktɪveɪtɪd",ko:"기능이 꺼진"},
  "deadline": {ipa:"ˈdedlaɪn",ko:"마감 시각"},
  "decide": {ipa:"dɪˈsaɪd",ko:"정하다"},
  "decided": {ipa:"dɪˈsaɪdəd",ko:"정했다"},
  "declaration": {ipa:"ˌdɛkləˈɹeɪʃən",ko:"신고"},
  "declare": {ipa:"dɪˈkleə",ko:"신고하다"},
  "declined": {ipa:"dɪˈklaɪnd",ko:"승인 거절된"},
  "degree": {ipa:"dɪˈɡɹiː",ko:"정도"},
  "delay": {ipa:"dɪˈleɪ",ko:"지연"},
  "delayed": {ipa:"dəˈleɪd",ko:"지연된",pron:"딜[레이]드"},
  "delicious": {ipa:"dɪˈlɪʃəs",ko:"맛있는"},
  "deliver": {ipa:"dɪˈlɪvə(ɹ)",ko:"배달하다"},
  "delivery": {ipa:"dɪˈlɪv(ə)ɹi",ko:"배송"},
  "demagnetized": {ipa:"diːˈmæɡnətaɪzd",ko:"자기가 지워진"},
  "denied": {ipa:"dɪˈnaɪd",ko:"거절된"},
  "departed": {ipa:"dɪˈpɑːtɪd",ko:"떠났다"},
  "departing": {ipa:"dɪˈpɑːtɪŋ",ko:"떠나는"},
  "departure": {ipa:"dɪˈpɑːtʃə",ko:"출발"},
  "depend": {ipa:"dɪˈpɛnd",ko:"달려 있다"},
  "depends": {ipa:"dɪˈpɛndz",ko:"달려 있다"},
  "deposit": {ipa:"dɪˈpɒzɪt",ko:"보증금"},
  "desk": {ipa:"dɛsk",ko:"창구"},
  "dessert": {ipa:"dɪˈzɜːt",ko:"디저트"},
  "destination": {ipa:"dɛstɪˈneɪʃən",ko:"목적지"},
  "details": {ipa:"dɪˈteɪlz",ko:"자세한 내용"},
  "detergent": {ipa:"dɪˈtɜːdʒənt",ko:"세제"},
  "did": {ipa:"dɪd"},
  "didn't": {ipa:"ˈdɪdənt"},
  "difference": {ipa:"ˈdɪfəɹən(t)s",ko:"차이",pron:"[디]퍼런스"},
  "different": {ipa:"ˈdɪf.(ə)ɹ.ənt",ko:"다른"},
  "differently": {ipa:"ˈdifəɹəntli",ko:"다르게"},
  "difficult": {ipa:"ˈdɪfɪkəlt",ko:"어려운"},
  "direct": {ipa:"d(a)ɪˈɹɛkt",ko:"안내하다"},
  "directions": {ipa:"dɪˈɹekʃənz",ko:"길 안내"},
  "disagree": {ipa:"dɪsəˈɡɹiː",ko:"동의하지 않다"},
  "disappointed": {ipa:"ˌdɪsəˈpɔɪntɪd",ko:"실망한"},
  "disappointment": {ipa:"dɪsəˈpɔɪntmənt",ko:"실망"},
  "discount": {ipa:"dɪsˈkaʊnt",ko:"할인"},
  "dish": {ipa:"dɪʃ",ko:"요리"},
  "distance": {ipa:"ˈdɪs.təns",ko:"거리"},
  "disturb": {ipa:"dɪsˈtɜːb",ko:"방해하다"},
  "disturbing": {ipa:"dɪsˈtɜːbɪŋ",ko:"방해하는"},
  "do": {ipa:"duː"},
  "doable": {ipa:"ˈduːəbl",ko:"할 만한"},
  "doctor": {ipa:"ˈdɒktə",ko:"의사",pron:"[닥]터"},
  "does": {ipa:"dʌz"},
  "doesn't": {ipa:"ˈdʌzənt"},
  "dog": {ipa:"dɑɡ",ko:"개",pron:"[도]그"},
  "doggy": {ipa:"ˈdɒ.ɡi",ko:"강아지"},
  "dogs": {ipa:"dɑɡz",ko:"개들",pron:"[도]그스"},
  "doing": {ipa:"ˈduːɪŋ",ko:"하는 중"},
  "don't": {ipa:"dəʊnt"},
  "done": {ipa:"dʌn"},
  "door": {ipa:"dɔːɹ",ko:"문"},
  "double": {ipa:"ˈdʌb.əl",ko:"두 번"},
  "doubtful": {ipa:"ˈdaʊtfəl",ko:"의심스러운"},
  "down": {ipa:"daʊn"},
  "draft": {ipa:"dɹæft",ko:"생맥주"},
  "drain": {ipa:"dɹeɪn",ko:"물이 빠지다"},
  "draught": {ipa:"dɹɑːft",ko:"생맥주"},
  "drifted": {ipa:"ˈdɹɪftɪd",ko:"멀어졌다"},
  "drink": {ipa:"dɹɪŋk",ko:"마시다"},
  "drinker": {ipa:"ˈdrɪŋkə",ko:"술 마시는 사람"},
  "drinking": {ipa:"ˈdɹɪŋkɪŋ",ko:"마시는"},
  "drinks": {ipa:"dɹɪŋks",ko:"음료"},
  "dripping": {ipa:"ˈdɹɪpɪŋ",ko:"물이 떨어지는"},
  "drive": {ipa:"dɹaɪv",ko:"운전하다"},
  "drop": {ipa:"dɹɒp",ko:"내려주다"},
  "dropping": {ipa:"ˈdɹɒpɪŋ",ko:"끊기는"},
  "dryer": {ipa:"ˈdɹaɪə",ko:"건조기"},
  "dull": {ipa:"dəl",ko:"따분한",pron:"[덜]"},
  "duty": {ipa:"ˈdjuːti",ko:"관세"},
  "duty-free": {ipa:"ˈdjuːti friː",ko:"면세의"},
  "dutyfree": {ipa:"ˈdjuːti friː",ko:"면세의"},
  "dwell": {ipa:"dwɛl",ko:"곱씹다"},
  "each": {ipa:"iːtʃ"},
  "earlier": {ipa:"ˈɜː.lɪə",ko:"더 일찍"},
  "early": {ipa:"ˈɜː.li",ko:"이른"},
  "earn": {ipa:"ɜːn",ko:"쌓다, 벌다"},
  "earphones": {ipa:"ˈɪəfoʊnz",ko:"이어폰"},
  "ease": {ipa:"iːz",ko:"편안함"},
  "easy": {ipa:"ˈiːzi",ko:"쉬운"},
  "easygoing": {ipa:"ˌiːziˈɡəʊɪŋ",ko:"느긋한"},
  "eat": {ipa:"iːt",ko:"먹다"},
  "eaten": {ipa:"ˈiːt(ə)n",ko:"먹었다"},
  "eating": {ipa:"ˈiːtɪŋ",ko:"신경 쓰이게 하는"},
  "eight": {ipa:"eɪt"},
  "either": {ipa:"ˈaɪðə"},
  "eldest": {ipa:"ˈeldɪst",ko:"맏이의"},
  "electronic": {ipa:"ɪˌlɛkˈtɹɒn.ɪk",ko:"전자의"},
  "elevator": {ipa:"ˈelɪveɪtə",ko:"엘리베이터"},
  "else": {ipa:"ɛls"},
  "email": {ipa:"ˈiːmeɪl",ko:"이메일"},
  "embassy": {ipa:"ˈɛmbəsi",ko:"대사관"},
  "empty": {ipa:"ˈɛmpti",ko:"비우다, 빈"},
  "end": {ipa:"ɛnd",ko:"끝"},
  "english": {ipa:"ˈɪŋɡlɪʃ",ko:"영어"},
  "enjoy": {ipa:"ənˈd͡ʒɔɪ",ko:"즐기다",pron:"인[조이]"},
  "enjoyed": {ipa:"ɪnˈdʒɔɪd",ko:"즐겼다"},
  "enough": {ipa:"ɪˈnʌf",ko:"충분한"},
  "enter": {ipa:"ˈɛntə(ɹ)",ko:"들어가다"},
  "entry": {ipa:"ˈɛntɹi",ko:"입국"},
  "envious": {ipa:"ˈɛnvɪəs",ko:"부러운"},
  "error": {ipa:"ˈeɹə",ko:"오류"},
  "especially": {ipa:"əˈspɛʃ(ə)li",ko:"특히"},
  "essentials": {ipa:"ɪˈsenʃəlz",ko:"생필품"},
  "even": {ipa:"ˈiːvən"},
  "evening": {ipa:"ˈivnɪŋ",ko:"저녁"},
  "everybody": {ipa:"ˈevɹibɒdi"},
  "everyone": {ipa:"ˈɛv.ɹi.wʌn"},
  "everything": {ipa:"ˈɛvɹiθɪŋ",ko:"모든 것"},
  "exactly": {ipa:"ɪɡˈzæktli",ko:"꼭, 정확히"},
  "example": {ipa:"əɡˈzæmpl̩",ko:"예",pron:"이그[잼]플"},
  "exceeded": {ipa:"ɪkˈsiːdɪd",ko:"넘어섰다"},
  "excellent": {ipa:"ˈɛksələnt",ko:"훌륭한"},
  "excess": {ipa:"əkˈsɛs",ko:"초과"},
  "exchange": {ipa:"ɛksˈtʃeɪndʒ",ko:"교환하다, 환전하다"},
  "excited": {ipa:"ɪkˈsaɪtɪd",ko:"신나는"},
  "excuse": {ipa:"ɪkˈskjuːz",ko:"실례"},
  "excused": {ipa:"ɛksˈkjuːzd",ko:"양해를 구한"},
  "exit": {ipa:"ˈeksɪt",ko:"출구, 비상구",pron:"[엑]시트"},
  "expect": {ipa:"ɛkˈspɛkt",ko:"기대하다"},
  "expectations": {ipa:"ɛkspɛkˈteɪʃənz",ko:"기대"},
  "expected": {ipa:"ɪksˈpɛktɪd",ko:"예상한"},
  "expensive": {ipa:"ɛkˈspɛnsɪv",ko:"비싼"},
  "explain": {ipa:"ɛkˈspleɪn",ko:"설명하다"},
  "explains": {ipa:"ɛkˈspleɪnz",ko:"설명하다"},
  "expressing": {ipa:"ɛk.ˈspɹɛsɪŋ",ko:"드러내는"},
  "extend": {ipa:"ɛkˈstɛnd",ko:"연장하다"},
  "extent": {ipa:"ɪksˈtɛnt",ko:"정도"},
  "extra": {ipa:"ˈɛkstɹə",ko:"추가의",pron:"[엑]스트라"},
  "eye": {ipa:"aɪ",ko:"눈"},
  "fabric": {ipa:"ˈfæb.ɹɪk",ko:"옷감"},
  "faces": {ipa:"ˈfeɪsɪz",ko:"마주 본다"},
  "fair": {ipa:"feə",ko:"공평한"},
  "falling-out": {ipa:"ˈfɔːlɪŋaʊt",ko:"다투고 멀어짐"},
  "familiar": {ipa:"fəˈmɪliə",ko:"낯익은"},
  "families": {ipa:"ˈfæməliz",ko:"가족들",pron:"[패]밀리즈"},
  "family": {ipa:"ˈfæməli",ko:"가족",pron:"[패]밀리"},
  "fantastic": {ipa:"fænˈtæstɪk",ko:"아주 훌륭한"},
  "far": {ipa:"fɑː",ko:"먼"},
  "fare": {ipa:"fɛə(ɹ)",ko:"교통 요금"},
  "farther": {ipa:"ˈfɑːðə",ko:"더 멀리"},
  "fast": {ipa:"fɑːst",ko:"빠른",pron:"[패]스트"},
  "fasten": {ipa:"ˈfɑːsn̩",ko:"매다",pron:"[패]슨"},
  "father": {ipa:"ˈfɑːðə",ko:"아버지"},
  "father's": {ipa:"ˈfɑːðəz",ko:"아버지의"},
  "faucet": {ipa:"ˈfɔːsɪt",ko:"수도꼭지"},
  "fault": {ipa:"fɒlt",ko:"잘못"},
  "favor": {ipa:"ˈfeɪvə",ko:"부탁"},
  "favour": {ipa:"ˈfeɪ.və",ko:"부탁"},
  "fed": {ipa:"fɛd",ko:"질린"},
  "fee": {ipa:"fiː",ko:"수수료"},
  "feel": {ipa:"fiːl",ko:"느끼다"},
  "feeling": {ipa:"ˈfiːlɪŋ",ko:"기분"},
  "feelings": {ipa:"ˈfiːlɪŋz",ko:"감정"},
  "feels": {ipa:"fiːlz",ko:"느껴지다"},
  "fell": {ipa:"fɛl",ko:"떨어졌다"},
  "fence": {ipa:"fens",ko:"울타리"},
  "fight": {ipa:"faɪt",ko:"다툼"},
  "file": {ipa:"faɪl",ko:"접수하다"},
  "fill": {ipa:"fɪl",ko:"채우다"},
  "final": {ipa:"ˈfaɪ.nəl",ko:"최종의"},
  "finally": {ipa:"ˈfaɪ.nəl.i",ko:"마침내"},
  "find": {ipa:"faɪnd",ko:"찾다"},
  "fine": {ipa:"faɪn",ko:"괜찮은"},
  "finger": {ipa:"ˈfɪŋɡəɹ",ko:"손가락"},
  "fingerprints": {ipa:"ˈfɪŋɡəpɹɪnts",ko:"지문"},
  "fingers": {ipa:"ˈfɪŋɡəz",ko:"손가락"},
  "finish": {ipa:"ˈfɪnɪʃ",ko:"끝나다"},
  "finished": {ipa:"ˈfɪnɪʃt",ko:"끝난"},
  "firm": {ipa:"fɜːm",ko:"단단한"},
  "first": {ipa:"fɜːst",ko:"첫 번째"},
  "fit": {ipa:"fɪt",ko:"끼워 넣다"},
  "fitting": {ipa:"ˈfɪtɪŋ",ko:"옷을 입어보는"},
  "five": {ipa:"faɪv"},
  "flies": {ipa:"flaɪz",ko:"날아가다"},
  "flight": {ipa:"flaɪt",ko:"항공편"},
  "floor": {ipa:"flɔːɹ",ko:"층"},
  "flow": {ipa:"fləʊ",ko:"흐름",pron:"[플로]우"},
  "flush": {ipa:"ˈflʌʃ",ko:"물을 내리다"},
  "flyer": {ipa:"ˈflaɪə",ko:"자주 타는 손님"},
  "flying": {ipa:"ˈflaɪ.ɪŋ",ko:"비행하는"},
  "follow": {ipa:"ˈfɒləʊ",ko:"따라가다",pron:"[팔]로우"},
  "food": {ipa:"fuːd",ko:"음식"},
  "foot": {ipa:"fʊt",ko:"발"},
  "footsteps": {ipa:"ˈfʊtsteps",ko:"발자취"},
  "for": {ipa:"fɔː"},
  "foreigners": {ipa:"ˈfɒɹɪnəz",ko:"외국인들"},
  "forever": {ipa:"fəˈɹɛvə(ɹ)",ko:"영원히",pron:"퍼[에]버"},
  "forget": {ipa:"fəˈɡɛt",ko:"잊다"},
  "forgot": {ipa:"fəˈɡɒt",ko:"잊었다"},
  "fork": {ipa:"fɔːk",ko:"포크"},
  "form": {ipa:"fɔːm",ko:"서류"},
  "forward": {ipa:"ˈfɔːwəd",ko:"앞으로"},
  "found": {ipa:"faʊnd",ko:"찾았다"},
  "four": {ipa:"foː"},
  "fragile": {ipa:"ˈfɹædʒaɪl",ko:"깨지기 쉬운"},
  "frank": {ipa:"fɹæŋk",ko:"솔직한"},
  "frankly": {ipa:"ˈfɹæŋkli",ko:"솔직히"},
  "free": {ipa:"fɹiː",ko:"비어 있는, 무료의"},
  "frequent": {ipa:"ˈfɹiː.kwənt",ko:"잦은"},
  "fridge": {ipa:"fɹɪd͡ʒ",ko:"냉장고"},
  "friend": {ipa:"fɹɛnd",ko:"친구"},
  "friendly": {ipa:"ˈfɹɛndli",ko:"친절한"},
  "friends": {ipa:"fɹɛn(d)z",ko:"친구들"},
  "from": {ipa:"fɹɒm"},
  "front": {ipa:"fɹʌnt",ko:"앞쪽"},
  "frustrating": {ipa:"ˈfɹʌstɹeɪtɪŋ",ko:"답답한"},
  "full": {ipa:"fʊl",ko:"가득한"},
  "full-time": {ipa:"ˌfʊlˈtaɪm",ko:"온종일 일하는"},
  "fulltime": {ipa:"ˌfʊlˈtaɪm",ko:"온종일 일하는"},
  "fun": {ipa:"fʊn",ko:"재미",pron:"[펀]"},
  "funny": {ipa:"ˈfʌni",ko:"웃긴"},
  "further": {ipa:"ˈfɜːðə",ko:"더 멀리"},
  "gap": {ipa:"ɡæp",ko:"차이"},
  "gate": {ipa:"ɡeɪt",ko:"탑승구"},
  "gathering": {ipa:"ˈɡæ.ðə.ɹɪŋ",ko:"모임"},
  "gave": {ipa:"ɡeɪv",ko:"주었다"},
  "gentle": {ipa:"ˈdʒɛntl̩",ko:"순한"},
  "genuine": {ipa:"ˈdʒɛnjuːˌaɪn",ko:"진짜의"},
  "genuinely": {ipa:"ˈdʒenjuɪnli",ko:"정말로"},
  "get": {ipa:"ɡɛt",ko:"얻다, 되다"},
  "getting": {ipa:"[ˈɡɛɾɪŋ]",ko:"되어가는",pron:"[게]팅"},
  "gift": {ipa:"ɡɪft",ko:"선물"},
  "gift-wrap": {ipa:"ˈɡɪft ræp",ko:"선물 포장하다"},
  "gifts": {ipa:"ɡɪfts",ko:"선물"},
  "girl": {ipa:"ɡɜːl",ko:"여자아이"},
  "give": {ipa:"ɡɪv",ko:"주다"},
  "glad": {ipa:"ɡlæd",ko:"기쁜"},
  "glance": {ipa:"ɡlɑːns",ko:"훑어봄",pron:"[글랜]스"},
  "glass": {ipa:"ɡlɑːs",ko:"유리잔"},
  "glasses": {ipa:"ˈɡlasɪz",ko:"안경"},
  "glorious": {ipa:"ˈɡlɔː.ɹi.əs",ko:"눈부신"},
  "go": {ipa:"ɡəʊ",ko:"가다"},
  "goes": {ipa:"ɡəʊz",ko:"가다"},
  "going": {ipa:"ˈɡəʊɪŋ",ko:"가는 중"},
  "gone": {ipa:"ɡɔːn"},
  "good": {ipa:"ɡʊd",ko:"좋은",pron:"[굿]"},
  "gorgeous": {ipa:"ˈɡɔːdʒəs",ko:"아주 좋은"},
  "got": {ipa:"ɡɒt",ko:"얻었다",pron:"[갓]"},
  "gotten": {ipa:"ˈɡɒtn̩",ko:"~하게 되었다"},
  "grab": {ipa:"ɡɹæb",ko:"간단히 먹다, 잡다"},
  "grandchildren": {ipa:"ˈɡɹæntʃɪldɹən",ko:"손주들",pron:"그랜[칠]드런"},
  "grandkids": {ipa:"ˈɡɹænkɪdz",ko:"손주들"},
  "grandma": {ipa:"ˈɡɹænmɑː",ko:"할머니"},
  "grandmother": {ipa:"ˈɡɹænmʌðə",ko:"할머니"},
  "grateful": {ipa:"ˈɡɹeɪtfəl",ko:"고마워하는"},
  "gratuity": {ipa:"ɡɹəˈtjuːətɪ",ko:"봉사료"},
  "greasy": {ipa:"ˈɡɹi.zi",ko:"기름진"},
  "great": {ipa:"ɡɹeɪt",ko:"훌륭한"},
  "green": {ipa:"ɡɹiːn",ko:"초록의"},
  "grew": {ipa:"ɡɹuː",ko:"자랐다"},
  "group": {ipa:"ɡɹuːp",ko:"무리",pron:"[그룹]"},
  "grow": {ipa:"ɡɹəʊ",ko:"자라다"},
  "grown": {ipa:"ɡɹəʊn",ko:"다 자란"},
  "guy": {ipa:"ɡaɪ",ko:"남자, 사람"},
  "guys": {ipa:"ɡaɪz",ko:"남자들"},
  "gym": {ipa:"dʒɪm",ko:"헬스장"},
  "had": {ipa:"hæd"},
  "hail": {ipa:"heɪl",ko:"택시를 잡다"},
  "hair": {ipa:"heː",ko:"머리카락",pron:"[헤]어"},
  "haircut": {ipa:"ˈheəkʌt",ko:"이발"},
  "hall": {ipa:"hɔːl",ko:"회관"},
  "hallway": {ipa:"ˈhɔːlweɪ",ko:"복도"},
  "hand": {ipa:"hænd",ko:"손, 도움"},
  "handle": {ipa:"ˈhæn.dl",ko:"감당하다"},
  "handled": {ipa:"ˈhændl̩d",ko:"처리했다"},
  "hanging": {ipa:"ˈhæŋɪŋ",ko:"버티는"},
  "happen": {ipa:"ˈhæpən",ko:"일어나다"},
  "happened": {ipa:"ˈhæpənd",ko:"일어났다"},
  "happens": {ipa:"ˈhæpənz",ko:"일어난다"},
  "happy": {ipa:"ˈhæpi",ko:"행복한"},
  "hard": {ipa:"hɑːd",ko:"어려운"},
  "harder": {ipa:"ˈhɑːdə",ko:"더 어려운"},
  "has": {ipa:"hæz"},
  "hasn't": {ipa:"ˈhæzənt"},
  "hassle": {ipa:"ˈhæsəl",ko:"번거로운 일"},
  "hat": {ipa:"hæt",ko:"모자"},
  "hate": {ipa:"heɪt",ko:"싫어하다"},
  "have": {ipa:"hæv"},
  "haven't": {ipa:"ˈhævənt"},
  "having": {ipa:"ˈhævɪŋ"},
  "he": {ipa:"hiː"},
  "he'll": {ipa:"hiːl"},
  "he's": {ipa:"hiːz"},
  "head": {ipa:"hɛd",ko:"향해 가다"},
  "heading": {ipa:"ˈhedɪŋ",ko:"향하는"},
  "headphones": {ipa:"ˈhedfoʊnz",ko:"헤드폰"},
  "heads-up": {ipa:"ˌhedzˈʌp",ko:"미리 알려주기",pron:"헤즈[업]"},
  "headsup": {ipa:"ˌhedzˈʌp",ko:"미리 알려주기"},
  "hear": {ipa:"hɪə(ɹ)",ko:"듣다"},
  "heard": {ipa:"hɜːd",ko:"들었다"},
  "hearing": {ipa:"ˈhiːɹ.ɪŋ",ko:"듣기"},
  "heat": {ipa:"hit",ko:"데우다",pron:"[히]트"},
  "heater": {ipa:"ˈhiːtə",ko:"난방기"},
  "heating": {ipa:"ˈhiːtɪŋ",ko:"난방"},
  "heavy": {ipa:"ˈhevi",ko:"무거운, 심한"},
  "hectic": {ipa:"ˈhɛktɪk",ko:"정신없는"},
  "hello": {ipa:"həˈləʊ",ko:"안녕하세요",pron:"헐[로]"},
  "help": {ipa:"hɛlp",ko:"돕다, 도움"},
  "helped": {ipa:"helpt",ko:"도와줬다"},
  "helpful": {ipa:"ˈhɛlp.fəl",ko:"도움이 되는",pron:"[헬]프풀"},
  "helping": {ipa:"ˈhɛlpɪŋ",ko:"돕는"},
  "helps": {ipa:"hɛlps",ko:"도움이 된다"},
  "her": {ipa:"hɜː"},
  "here": {ipa:"hɪə"},
  "here's": {ipa:"hɪəz"},
  "herself": {ipa:"hɜːˈsɛlf"},
  "hesitant": {ipa:"ˈhɛzɪtənt",ko:"망설이는"},
  "hesitate": {ipa:"ˈhɛzɪteɪt",ko:"망설이다"},
  "hi": {ipa:"haɪ",ko:"안녕"},
  "high": {ipa:"haɪ",ko:"높은"},
  "hiking": {ipa:"ˈhaɪkɪŋ",ko:"등산"},
  "him": {ipa:"hɪm"},
  "himself": {ipa:"hɪmˈsɛlf"},
  "his": {ipa:"hɪz"},
  "hit": {ipa:"hɪt",ko:"누르다",pron:"[히]트"},
  "hits": {ipa:"hɪts",ko:"와닿는다",pron:"[히]츠"},
  "hold": {ipa:"həʊld",ko:"붙잡다, 보관하다"},
  "holiday": {ipa:"ˈhɒlɪdeɪ",ko:"휴가, 연휴"},
  "holidays": {ipa:"ˈhɒlɪdeɪz",ko:"명절, 휴일"},
  "home": {ipa:"həʊm",ko:"집"},
  "honest": {ipa:"ˈɒnɪst",ko:"솔직한",pron:"[어]니스트"},
  "honestly": {ipa:"ˈɒnɪstli",ko:"솔직히",pron:"[어]니스틀리"},
  "hope": {ipa:"həʊp",ko:"바라다"},
  "hoped": {ipa:"həʊpt",ko:"바랐다"},
  "hopeful": {ipa:"ˈhəʊpfəl",ko:"희망적인",pron:"[호]프풀"},
  "hopes": {ipa:"həʊps",ko:"기대"},
  "horizontally": {ipa:"ˌhɒɹɪˈzɒntəli",ko:"가로로"},
  "hot": {ipa:"hɒt",ko:"뜨거운, 매운",pron:"[핫]"},
  "hotel": {ipa:"həʊˈtel",ko:"호텔"},
  "house": {ipa:"haʊs",ko:"집"},
  "housekeeping": {ipa:"ˈhaʊskiːpɪŋ",ko:"객실 정리"},
  "how": {ipa:"haʊ"},
  "how's": {ipa:"haʊz"},
  "humid": {ipa:"ˈhjuːmɪd",ko:"습한"},
  "hung": {ipa:"ˈhʌŋ",ko:"어울렸다"},
  "hurry": {ipa:"ˈhʌ.ɹi",ko:"서두름"},
  "hurt": {ipa:"hɜːt",ko:"상하게 하다"},
  "husband": {ipa:"ˈhʌzbənd",ko:"남편"},
  "hype": {ipa:"haɪp",ko:"부풀려진 기대"},
  "i": {ipa:"aɪ"},
  "i'd": {ipa:"aɪd"},
  "i'll": {ipa:"aɪl"},
  "i'm": {ipa:"aɪm"},
  "i've": {ipa:"aɪv"},
  "ice": {ipa:"aɪs",ko:"얼음"},
  "icy": {ipa:"ˈaɪsi",ko:"얼어붙은"},
  "id": {ipa:"ɪd",ko:"신분증",pron:"아이[디]"},
  "idea": {ipa:"aɪˈdɪə",ko:"생각"},
  "if": {ipa:"ɪf"},
  "imagine": {ipa:"ɪˈmædʒ.ɪn",ko:"상상하다"},
  "immigration": {ipa:"ɪmɪˈɡɹeɪʃən",ko:"입국심사"},
  "impatient": {ipa:"ɪmˈpeɪʃənt",ko:"성격이 급한"},
  "impose": {ipa:"ɪmˈpəʊz",ko:"폐를 끼치다"},
  "impressed": {ipa:"ɪmˈpɹɛst",ko:"감탄한"},
  "impressive": {ipa:"ɪmˈpɹɛsɪv",ko:"인상적인"},
  "in": {ipa:"ɪn"},
  "in-laws": {ipa:"ˈɪnlɔːz",ko:"결혼으로 맺어진 가족"},
  "include": {ipa:"ɪnˈkluːd",ko:"포함하다"},
  "included": {ipa:"ɪnˈkluːdɪd",ko:"포함된"},
  "includes": {ipa:"ɪnˈkluːdz",ko:"포함한다"},
  "infants": {ipa:"ˈɪnfənts",ko:"젖먹이"},
  "info": {ipa:"ˈɪnfəʊ",ko:"정보"},
  "information": {ipa:"ˌɪnfəˈmeɪʃən",ko:"정보"},
  "insect": {ipa:"ˈɪnsɛkt",ko:"곤충"},
  "inside": {ipa:"ɪnˈsaɪd"},
  "inspect": {ipa:"ɪnˈspɛkt",ko:"살펴보다"},
  "installments": {ipa:"ɪnˈstɔːlmənts",ko:"할부"},
  "instead": {ipa:"ɪnˈstɛd",ko:"대신에"},
  "interested": {ipa:"ˈɪntəɹɛstəd",ko:"관심 있는"},
  "interesting": {ipa:"ˈɪnt(ə)ɹɛstɪŋ",ko:"흥미로운"},
  "interpreter": {ipa:"ɪnˈtɜːpɹɪtə",ko:"통역사"},
  "interrupt": {ipa:"ˌɪntəˈɹʌpt",ko:"말을 끊다"},
  "interrupting": {ipa:"ˌɪntəˈrʌptɪŋ",ko:"방해하는"},
  "interview": {ipa:"ˈɪntəvjuː",ko:"면접"},
  "into": {ipa:"ˈɪn.tuː"},
  "introduce": {ipa:"ˌɪntɹəˈdjuːs",ko:"소개하다",pron:"인트로[듀]스"},
  "invite": {ipa:"ɪnˈvaɪt",ko:"부르다"},
  "iron": {ipa:"ˈaɪən",ko:"다리미",pron:"[아이]언"},
  "ironing": {ipa:"ˈaɪənɪŋ",ko:"다림질"},
  "is": {ipa:"ɪz"},
  "isn't": {ipa:"ˈɪzənt"},
  "it": {ipa:"ɪt"},
  "it'll": {ipa:"ˈɪtəl"},
  "it's": {ipa:"ɪts"},
  "item": {ipa:"[ˈaɪ̯ɾm̩]",ko:"항목, 물건",pron:"[아이]템"},
  "jealous": {ipa:"ˈdʒɛləs",ko:"부러운"},
  "job": {ipa:"d͡ʒɒb",ko:"직장",pron:"[잡]"},
  "jobs": {ipa:"d͡ʒɒbz",ko:"직장",pron:"[잡]스"},
  "join": {ipa:"ˈdʒɔɪn",ko:"함께하다"},
  "joking": {ipa:"ˈdʒəʊkɪŋ",ko:"농담하는"},
  "journey": {ipa:"ˈd͡ʒɜːni",ko:"여정"},
  "judge": {ipa:"dʒʌdʒ",ko:"판단하다"},
  "jun": {ipa:"dʒʌn",pron:"[준]"},
  "just": {ipa:"d͡ʒʌst"},
  "keen": {ipa:"kiːn",ko:"관심 있는"},
  "keep": {ipa:"kiːp",ko:"유지하다, 맡다",pron:"[킵]"},
  "keeping": {ipa:"ˈkiːpɪŋ",ko:"지키는"},
  "keeps": {ipa:"kiːps",ko:"계속 ~하다",pron:"[킵]스"},
  "key": {ipa:"kiː",ko:"열쇠"},
  "kid": {ipa:"kɪd",ko:"아이"},
  "kidding": {ipa:"ˈkɪdɪŋ",ko:"농담하는"},
  "kids": {ipa:"kɪ(d)z",ko:"아이들"},
  "kim": {ipa:"kɪm"},
  "kind": {ipa:"kaɪnd",ko:"종류, 친절한"},
  "kiosks": {ipa:"ˈkiːɒsks",ko:"무인 기계"},
  "kitchen": {ipa:"ˈkɪt͡ʃən",ko:"주방",pron:"[키]친"},
  "knew": {ipa:"ˈnjuː",ko:"알았다"},
  "know": {ipa:"nəʊ",ko:"알다"},
  "known": {ipa:"nəʊn",ko:"알고 지낸"},
  "knows": {ipa:"nəʊz",ko:"안다"},
  "korean": {ipa:"kəˈriːən",ko:"한국어",pron:"코[리]안"},
  "lady": {ipa:"ˈleɪdi",ko:"여자분"},
  "laid-back": {ipa:"ˌleɪdˈbæk",ko:"느긋한"},
  "landing": {ipa:"ˈlændɪŋ",ko:"착륙"},
  "laptop": {ipa:"ˈlæp.tɒp",ko:"노트북"},
  "larger": {ipa:"ˈlɑː.d͡ʒə",ko:"더 큰"},
  "last": {ipa:"last",ko:"지난, 마지막"},
  "lasted": {ipa:"ˈlastɪd",ko:"이어졌다"},
  "late": {ipa:"leɪt",ko:"늦은"},
  "lately": {ipa:"ˈleɪt.li",ko:"요즘"},
  "later": {ipa:"ˈleɪtə",ko:"나중에"},
  "laundry": {ipa:"ˈlɑn.dɹi",ko:"세탁",pron:"[론]드리"},
  "lavatory": {ipa:"ˈlæv.ə.təɹ.i",ko:"기내 화장실"},
  "law": {ipa:"lɔː",ko:"법"},
  "layover": {ipa:"ˈleɪoʊvə",ko:"환승 대기"},
  "leads": {ipa:"liːdz",ko:"이끈다"},
  "leaking": {ipa:"ˈliːkɪŋ",ko:"새는"},
  "learned": {ipa:"ˈlɜːnd",ko:"배웠다"},
  "learning": {ipa:"ˈlɜːnɪŋ"},
  "learnt": {ipa:"ˈlɜːnt",ko:"배웠다"},
  "least": {ipa:"liːst",ko:"적어도"},
  "leave": {ipa:"liːv",ko:"남기다, 떠나다"},
  "left": {ipa:"lɛft",ko:"왼쪽, 두고 왔다"},
  "legroom": {ipa:"ˈleɡɹuːm",ko:"다리 공간"},
  "lend": {ipa:"lɛnd",ko:"빌려주다"},
  "less": {ipa:"lɛs",ko:"덜"},
  "lesson": {ipa:"ˈlesən",ko:"교훈"},
  "let": {ipa:"lɛt",ko:"~하게 하다"},
  "let's": {ipa:"lɛts"},
  "letdown": {ipa:"ˈletdaʊn",ko:"실망"},
  "level": {ipa:"ˈlɛv.əl",ko:"층, 수준",pron:"[레]벨"},
  "lifesaver": {ipa:"ˈlaɪfseɪvə",ko:"은인"},
  "lift": {ipa:"lɪft",ko:"엘리베이터, 태워주기"},
  "light": {ipa:"laɪt",ko:"불, 등"},
  "lighter": {ipa:"ˈlaɪtə",ko:"더 밝은"},
  "like": {ipa:"laɪk",ko:"같은, 좋아하다"},
  "limit": {ipa:"ˈlɪmɪt",ko:"한도"},
  "line": {ipa:"laɪn",ko:"줄"},
  "liquid": {ipa:"ˈlɪkwɪd",ko:"액체"},
  "list": {ipa:"lɪst",ko:"명단"},
  "listen": {ipa:"ˈlɪs.ən",ko:"듣다"},
  "listening": {ipa:"ˈlɪs.nɪŋ",ko:"귀 기울여 듣기"},
  "little": {ipa:"ˈlɪtəl",ko:"조금, 작은"},
  "live": {ipa:"lɪv",ko:"살다"},
  "lived": {ipa:"lɪvd",ko:"살았다"},
  "lives": {ipa:"lɪvz",ko:"산다"},
  "living": {ipa:"ˈlɪvɪŋ",ko:"생계, 사는"},
  "load": {ipa:"ləʊd",ko:"짐, 부담"},
  "location": {ipa:"ləʊˈkeɪʃən",ko:"지점"},
  "lock": {ipa:"lɒk",ko:"잠그다"},
  "locked": {ipa:"lɒkt",ko:"잠갔다"},
  "long": {ipa:"ˈlɔːŋ",ko:"긴, 오래"},
  "longer": {ipa:"ˈlɑŋ.ɡɚ",ko:"더 오래",pron:"[롱]거"},
  "look": {ipa:"lʊk",ko:"보다"},
  "looked": {ipa:"lʊkt",ko:"살폈다"},
  "looking": {ipa:"ˈlʊkɪŋ",ko:"보는 중"},
  "looks": {ipa:"lʊks",ko:"~해 보이다"},
  "lose": {ipa:"luːz",ko:"잃다"},
  "loss": {ipa:"lɑs",ko:"잃음",pron:"[로]스"},
  "lost": {ipa:"lɒst",ko:"잃어버린, 길을 잃은"},
  "lot": {ipa:"lɒt",ko:"많음",pron:"[랏]"},
  "loud": {ipa:"laʊd",ko:"소리 내어"},
  "louder": {ipa:"ˈlaʊdə",ko:"더 크게"},
  "lounge": {ipa:"laʊndʒ",ko:"라운지"},
  "love": {ipa:"lʊv",ko:"좋아하다",pron:"[러]브"},
  "lovely": {ipa:"ˈlʌvli",ko:"좋은, 사랑스러운"},
  "low": {ipa:"ləʊ",ko:"낮은"},
  "lower": {ipa:"ˈləʊə",ko:"내리다"},
  "loyalty": {ipa:"ˈlɔɪəlti",ko:"단골 우대"},
  "luggage": {ipa:"ˈlʌɡɪd͡ʒ",ko:"짐"},
  "lukewarm": {ipa:"ˌluːkˈwɔːm",ko:"미지근한",pron:"루크[웜]"},
  "lunch": {ipa:"lʌnt͡ʃ",ko:"점심"},
  "machine": {ipa:"məˈʃin",ko:"기계"},
  "machines": {ipa:"məˈʃiːnz",ko:"기계들"},
  "made": {ipa:"meɪd",ko:"만들었다, 정돈했다"},
  "make": {ipa:"meɪk",ko:"만들다"},
  "makes": {ipa:"meɪks",ko:"만들다"},
  "man": {ipa:"mæn",ko:"남자"},
  "manageable": {ipa:"ˈmænɪd͡ʒəbl̩",ko:"감당할 만한"},
  "manager": {ipa:"ˈmænɪdʒə",ko:"관리자"},
  "many": {ipa:"ˈmæni"},
  "map": {ipa:"mæp",ko:"지도"},
  "marked": {ipa:"ˈmɑːkɪd",ko:"표시된"},
  "married": {ipa:"ˈmæɹ.ɪd",ko:"결혼한"},
  "material": {ipa:"məˈtɪəɹiəl",ko:"소재"},
  "matter": {ipa:"ˈmætə",ko:"중요하다"},
  "mattress": {ipa:"ˈmætɹɪs",ko:"매트리스"},
  "may": {ipa:"meɪ"},
  "me": {ipa:"miː"},
  "meal": {ipa:"miːl",ko:"식사"},
  "mean": {ipa:"miːn",ko:"뜻하다"},
  "meant": {ipa:"ment",ko:"뜻했다"},
  "meat": {ipa:"miːt",ko:"고기"},
  "medication": {ipa:"mɛdɪˈkeɪʃən",ko:"약"},
  "medicine": {ipa:"ˈmed(ɪ).sn̩",ko:"약"},
  "medium": {ipa:"ˈmiːdɪəm",ko:"중간의"},
  "meet": {ipa:"miːt",ko:"만나다"},
  "meeting": {ipa:"ˈmiːtɪŋ",ko:"만남"},
  "membership": {ipa:"ˈmembəʃɪp",ko:"회원"},
  "men": {ipa:"men",ko:"남자들"},
  "mention": {ipa:"ˈmɛnʃən",ko:"언급하다"},
  "menu": {ipa:"ˈmɛnju",ko:"메뉴판"},
  "message": {ipa:"ˈmɛsɪd͡ʒ",ko:"메시지"},
  "met": {ipa:"met",ko:"만났다"},
  "meter": {ipa:"ˈmiːtə",ko:"미터기"},
  "metro": {ipa:"ˈmɛtɹəʊ",ko:"지하철"},
  "microwave": {ipa:"ˈmaɪkɹəweɪv",ko:"전자레인지"},
  "middle": {ipa:"ˈmɪdəl",ko:"가운데"},
  "might": {ipa:"maɪt"},
  "mileage": {ipa:"ˈmaɪlɪdʒ",ko:"마일리지"},
  "miles": {ipa:"maɪlz",ko:"마일리지"},
  "milk": {ipa:"mɪlk",ko:"우유"},
  "mind": {ipa:"maɪnd",ko:"꺼리다, 마음"},
  "mine": {ipa:"maɪn"},
  "minibar": {ipa:"ˈmɪnibɑː",ko:"미니바"},
  "minsu": {ipa:"ˈminsuː"},
  "minute": {ipa:"ˈmɪnɪt",ko:"분, 잠깐"},
  "minutes": {ipa:"ˈmɪnɪts",ko:"분"},
  "mirror": {ipa:"ˈmɪɹə",ko:"거울"},
  "miss": {ipa:"mɪs",ko:"놓치다"},
  "missed": {ipa:"mɪst",ko:"놓쳤다"},
  "missing": {ipa:"ˈmɪsɪŋ",ko:"없어진"},
  "mistake": {ipa:"mɪˈsteɪk",ko:"실수"},
  "mistaken": {ipa:"mɪˈsteɪkən",ko:"잘못 알고 있는"},
  "misunderstanding": {ipa:"ˌmɪsʌndəˈstændɪŋ",ko:"오해",pron:"미스언더[스탠]딩"},
  "misunderstood": {ipa:"ˌmɪs.ʌn.dəˈstʊd",ko:"잘못 알아들었다",pron:"미스언더[스투]드"},
  "mixed": {ipa:"mɪkst",ko:"뒤섞인"},
  "mode": {ipa:"məʊd",ko:"모드"},
  "model": {ipa:"ˈmɒdl̩",ko:"본보기",pron:"[모]델"},
  "mom": {ipa:"mɑːm",ko:"엄마"},
  "moment": {ipa:"ˈməʊmənt",ko:"잠깐"},
  "monday": {ipa:"ˈmʌndeɪ",ko:"월요일"},
  "money": {ipa:"ˈmʌni",ko:"돈"},
  "month": {ipa:"mʌnθ",ko:"달"},
  "more": {ipa:"ˈmɔːɹ"},
  "morning": {ipa:"ˈmɔːnɪŋ",ko:"아침"},
  "mother": {ipa:"ˈmʌðə",ko:"어머니"},
  "motivation": {ipa:"ˌməʊtɪˈveɪʃən",ko:"의욕"},
  "move": {ipa:"muːv",ko:"옮기다"},
  "moved": {ipa:"muːvd",ko:"감동한, 옮겼다"},
  "movie": {ipa:"ˈmuːvi",ko:"영화"},
  "much": {ipa:"mʌt͡ʃ"},
  "music": {ipa:"ˈmjuːzɪk",ko:"음악"},
  "must": {ipa:"mʌst"},
  "musty": {ipa:"ˈmʌsti",ko:"퀴퀴한"},
  "my": {ipa:"maɪ"},
  "myself": {ipa:"maɪˈsɛlf",ko:"나 자신"},
  "name": {ipa:"neɪm",ko:"이름"},
  "named": {ipa:"neɪmd",ko:"이름 지어진"},
  "napkins": {ipa:"ˈnæpkɪnz",ko:"냅킨"},
  "nauseous": {ipa:"ˈnɑːʃəs",ko:"메스꺼운",pron:"[노]셔스"},
  "near": {ipa:"nɪə(ɹ)"},
  "nearby": {ipa:"ˌnɪəˈbaɪ",ko:"근처의"},
  "nearest": {ipa:"ˈnɪəɹɪst",ko:"가장 가까운"},
  "necessary": {ipa:"ˈnɛsəsɹɪ",ko:"필요한",pron:"[네]서세리"},
  "need": {ipa:"niːd",ko:"필요하다"},
  "needs": {ipa:"niːdz",ko:"필요로 한다"},
  "neighborhood": {ipa:"ˈneɪbəhʊd",ko:"동네"},
  "neighbors": {ipa:"ˈneɪbəz",ko:"이웃"},
  "neighbours": {ipa:"ˈneɪbəz",ko:"이웃"},
  "nephew": {ipa:"ˈnɛf.ju",ko:"남자 조카"},
  "nervous": {ipa:"ˈnɜːvəs",ko:"긴장한"},
  "never": {ipa:"ˈnɛv.ə(ɹ)"},
  "new": {ipa:"njuː",ko:"새로운"},
  "news": {ipa:"njuːz",ko:"소식"},
  "next": {ipa:"nɛkst",ko:"다음의"},
  "nice": {ipa:"naɪs",ko:"좋은"},
  "niece": {ipa:"niːs",ko:"여자 조카"},
  "night": {ipa:"naɪt",ko:"밤, 1박"},
  "nights": {ipa:"naɪts",ko:"밤"},
  "ninety": {ipa:"ˈnaɪn.ti",ko:"아흔"},
  "no": {ipa:"nəʊ"},
  "nobody": {ipa:"ˈnəʊbədi"},
  "noise": {ipa:"nɔɪz",ko:"소음"},
  "noisy": {ipa:"ˈnɔɪzi",ko:"시끄러운"},
  "non-alcoholic": {ipa:"ˌnɒnælkəˈhɒlɪk",ko:"무알코올의"},
  "non-smoking": {ipa:"nɒn ˈsmoʊkɪŋ",ko:"금연의"},
  "nonalcoholic": {ipa:"ˌnɒnælkəˈhɒlɪk",ko:"무알코올의"},
  "nonsmoking": {ipa:"nɒn ˈsmoʊkɪŋ",ko:"금연의"},
  "not": {ipa:"nɒt",pron:"[낫]"},
  "notes": {ipa:"nəʊts",ko:"메모",pron:"[노]츠"},
  "nothing": {ipa:"ˈnʌθɪŋ",ko:"아무것도 없음"},
  "now": {ipa:"naʊ",ipa:"naʊ",ko:"지금"},
  "now's": {ipa:"naʊz"},
  "nuisance": {ipa:"ˈnjuːsəns",ko:"성가신 사람"},
  "number": {ipa:"ˈnʌmbə",ko:"번호"},
  "occasion": {ipa:"əˈkeɪʒən",ko:"특별한 날"},
  "occupation": {ipa:"ɒkjəˈpeɪʃən",ko:"직업"},
  "of": {ipa:"əv"},
  "off": {ipa:"ɔːf"},
  "offended": {ipa:"əˈfɛndɪd",ko:"기분 상한"},
  "offer": {ipa:"ˈɑfɚ",ko:"제공하다",pron:"[오]퍼"},
  "office": {ipa:"ˈɑfɪs",ko:"사무실",pron:"[오]피스"},
  "often": {ipa:"ˈɑf(t)ən",ko:"자주",pron:"[오]프튼"},
  "oh": {ipa:"əʊ"},
  "oily": {ipa:"ˈɔɪli",ko:"기름기 도는"},
  "ok": {ipa:"ˌoʊˈkeɪ",ko:"괜찮은"},
  "okay": {ipa:"ˌəʊˈkeɪ",ko:"괜찮은"},
  "old": {ipa:"əʊld",ko:"오래된, 나이 든"},
  "older": {ipa:"ˈəʊldə",ko:"나이가 더 많은"},
  "oldest": {ipa:"ˈəʊldəst",ko:"맏이의"},
  "on": {ipa:"ɒn"},
  "one": {ipa:"wʌn"},
  "one's": {ipa:"wʌnz"},
  "ones": {ipa:"wʌnz"},
  "online": {ipa:"ɒnˈlaɪn",ko:"온라인으로"},
  "only": {ipa:"ˈəʊn.li"},
  "open": {ipa:"ˈəʊ.pən",ko:"열다"},
  "opening": {ipa:"ˈəʊ.pənɪŋ",ko:"빈자리"},
  "opinion": {ipa:"əˈpɪnjən",ko:"의견",pron:"어[피]니언"},
  "optimistic": {ipa:"ˌɒptɪˈmɪstɪk",ko:"낙관적인"},
  "options": {ipa:"ˈɒpʃənz",ko:"선택지"},
  "or": {ipa:"ɔː(ɹ)"},
  "order": {ipa:"ˈɔːdə",ko:"주문하다"},
  "ordered": {ipa:"ˈɔːdəd",ko:"주문했다"},
  "organise": {ipa:"ˈɔːɡənaɪz",ko:"정리하다"},
  "organize": {ipa:"ˈɔːɡənaɪz",ko:"정리하다"},
  "other": {ipa:"ˈʌðə"},
  "others": {ipa:"ˈʌðəz",ko:"다른 사람들"},
  "our": {ipa:"ˈaʊə"},
  "out": {ipa:"aʊt"},
  "outdoors": {ipa:"ˌaʊtˈdɔːz",ko:"야외에"},
  "outlet": {ipa:"ˈaʊtlet",ko:"콘센트"},
  "outside": {ipa:"ˌaʊtˈsaɪd",ko:"밖에"},
  "outweigh": {ipa:"ˌaʊtˈweɪ",ko:"더 크다"},
  "over": {ipa:"ˈəʊ.və(ɹ)"},
  "overhead": {ipa:"ˈəʊvəˌhɛd",ko:"머리 위의"},
  "overkill": {ipa:"ˈoʊvəkɪl",ko:"과한 것"},
  "overreacted": {ipa:"ˌəʊvəɹiˈæktɪd",ko:"지나치게 반응했다"},
  "overseas": {ipa:"ˌəʊvəˈsiːz",ko:"해외로"},
  "overweight": {ipa:"ˌoʊvəˈweɪt",ko:"무게 초과의"},
  "owe": {ipa:"əʊ",ko:"빚지다"},
  "own": {ipa:"əʊn",pron:"[오]운"},
  "packed": {ipa:"pækt",ko:"빡빡한"},
  "padlock": {ipa:"ˈpædlɒk",ko:"자물쇠"},
  "page": {ipa:"peɪd͡ʒ",ko:"쪽"},
  "pair": {ipa:"pɛə(ɹ)",ko:"한 쌍"},
  "parent": {ipa:"ˈpɛəɹənt",ko:"부모"},
  "parenting": {ipa:"ˈpɛəɹəntɪŋ",ko:"육아"},
  "parents": {ipa:"ˈpɛəɹənts",ko:"부모님"},
  "park": {ipa:"[paːk]",ko:"주차하다",pron:"[파]크"},
  "parking": {ipa:"ˈpɑːkɪŋ",ko:"주차"},
  "particularly": {ipa:"pəˈtɪkjəli",ko:"특별히",pron:"퍼[티]큘러리"},
  "pass": {ipa:"pɑːs",ko:"통행증, 건네다",pron:"[패]스"},
  "passes": {ipa:"ˈpɑːsɪz",ko:"탑승권",pron:"[패]시즈"},
  "passport": {ipa:"ˈpɑːspɔːt",ko:"여권",pron:"[패]스포트"},
  "password": {ipa:"ˈpæswɜːd",ko:"비밀번호"},
  "patient": {ipa:"ˈpeɪʃənt",ko:"참을성 있는"},
  "pay": {ipa:"peɪ",ko:"지불하다"},
  "peanuts": {ipa:"ˈpiːˌnʌts",ko:"땅콩"},
  "peek": {ipa:"piːk",ko:"살짝 보기"},
  "pen": {ipa:"pɛn",ko:"펜"},
  "people": {ipa:"ˈpiːpəl",ko:"사람들"},
  "per": {ipa:"pɜː(ɹ)",ko:"~당"},
  "permission": {ipa:"pəˈmɪʃən",ko:"허락"},
  "permitted": {ipa:"pəˈmɪtɪd",ko:"허용되는"},
  "person": {ipa:"ˈpɜːsən",ko:"사람"},
  "personal": {ipa:"ˈpɜː.sən.əl",ko:"개인의"},
  "personality": {ipa:"ˌpɜːsəˈnæləti",ko:"성격"},
  "personally": {ipa:"ˈpɜːsnəli",ko:"개인적으로"},
  "perspective": {ipa:"pɚˈspɛktɪv",ko:"관점"},
  "pest": {ipa:"pɛst",ko:"성가신 사람"},
  "pet": {ipa:"pɛt",ko:"반려동물"},
  "phone": {ipa:"fəʊ̯n",ko:"전화기"},
  "photo": {ipa:"ˈfəʊ.təʊ",ko:"사진"},
  "photos": {ipa:"ˈfəʊtəʊz",ko:"사진들"},
  "pick": {ipa:"pɪk",ko:"집어 들다"},
  "picture": {ipa:"ˈpɪktʃə",ko:"사진"},
  "pictures": {ipa:"ˈpɪktʃɚz",ko:"사진"},
  "pillow": {ipa:"ˈpɪləʊ",ko:"베개",pron:"[필]로우"},
  "pillows": {ipa:"ˈpɪləʊz",ko:"베개",pron:"[필]로우즈"},
  "pitch": {ipa:"pɪtʃ",ko:"거들다"},
  "pity": {ipa:"ˈpɪti",ko:"안타까움"},
  "place": {ipa:"pleɪs",ko:"장소, 대신"},
  "places": {ipa:"ˈpleɪsɪz",ko:"곳"},
  "plans": {ipa:"plænz",ko:"계획"},
  "plate": {ipa:"pleɪt",ko:"접시"},
  "play": {ipa:"pleɪ",ko:"놀다"},
  "plays": {ipa:"pleɪz",ko:"한다 (운동을)"},
  "pleasant": {ipa:"ˈplɛzənt",ko:"쾌적한"},
  "please": {ipa:"pliːz",ko:"부디"},
  "pleasure": {ipa:"ˈplɛʒə",ko:"기쁨"},
  "pockets": {ipa:"ˈpɒkɪts",ko:"주머니"},
  "point": {ipa:"pɔɪnt",ko:"요점"},
  "points": {ipa:"pɔɪnts",ko:"포인트"},
  "police": {ipa:"pəˈliːs",ko:"경찰",pron:"펄[리]스"},
  "pool": {ipa:"pul",ko:"수영장"},
  "portion": {ipa:"ˈpɔːʃən",ko:"1인분"},
  "position": {ipa:"pəˈzɪʃ(ə)n",ko:"위치, 자세"},
  "possible": {ipa:"ˈpɒsɪbl̩",ko:"가능한",pron:"[파]서블"},
  "postpone": {ipa:"poʊstˈpoʊn",ko:"미루다"},
  "pram": {ipa:"pɹæm",ko:"유모차"},
  "prefer": {ipa:"pɹɪˈfɜː",ko:"더 좋아하다"},
  "prescription": {ipa:"pɝˈskɹɪpʃən",ko:"처방전",pron:"프리스[크립]션"},
  "presents": {ipa:"ˈpɹɛzənts",ko:"선물"},
  "press": {ipa:"pɹɛs",ko:"누르다"},
  "pressing": {ipa:"ˈpɹɛsɪŋ",ko:"다림질"},
  "pressure": {ipa:"ˈpɹeʃə",ko:"압박, 수압"},
  "pretty": {ipa:"ˈpɹɪti",ko:"꽤"},
  "price": {ipa:"pɹaɪs",ko:"가격"},
  "priority": {ipa:"pɹaɪˈɒɹəti",ko:"우선"},
  "privacy": {ipa:"ˈpɹaɪv.ə.sɪ",ko:"사생활"},
  "probably": {ipa:"ˈpɹɒbli",ko:"아마",pron:"[프로]바블리"},
  "problem": {ipa:"ˈpɹɒbləm",ko:"문제"},
  "procedure": {ipa:"pɹəˈsiːdʒə",ko:"절차",pron:"프로[시]저"},
  "process": {ipa:"ˈpɹoʊsɛs",ko:"절차"},
  "products": {ipa:"ˈpɹɒd.əkts",ko:"제품"},
  "promotion": {ipa:"pɹəˈməʊʃən",ko:"승진",pron:"프로[모]션"},
  "properly": {ipa:"ˈpɹɒ.pə.li",ko:"제대로"},
  "pros": {ipa:"pɹəʊz",ko:"장점"},
  "public": {ipa:"ˈpʌblɪk",ko:"일반 사람들"},
  "pull": {ipa:"pʊl",ko:"당기다"},
  "pulling": {ipa:"ˈpʊlɪŋ",ko:"응원하는"},
  "purchase": {ipa:"ˈpɜːtʃəs",ko:"구입하다"},
  "purpose": {ipa:"ˈpɜːpəs",ko:"목적"},
  "push": {ipa:"[pʷʊʃ]",ko:"밀어붙이다"},
  "put": {ipa:"pʊt",ko:"놓다"},
  "queue": {ipa:"kjuː",ko:"줄"},
  "quick": {ipa:"kwɪk",ko:"빠른"},
  "quiet": {ipa:"ˈkwaɪ.ət",ko:"조용한"},
  "quieter": {ipa:"ˈkwaɪ.ə.tɚ",ko:"더 조용한"},
  "quote": {ipa:"kwəʊt",ko:"말을 그대로 옮기다"},
  "rain": {ipa:"ɹeɪn",ko:"비"},
  "rainy": {ipa:"ˈɹeɪni",ko:"비가 잦은"},
  "raise": {ipa:"ɹeɪz",ko:"들어올리다"},
  "raised": {ipa:"ɹeɪzd",ko:"키웠다"},
  "raising": {ipa:"ˈɹeɪzɪŋ",ko:"키우는 일"},
  "rank": {ipa:"ɹæŋk",ko:"택시 승강장"},
  "rare": {ipa:"ɹeə",ko:"덜 익힌"},
  "rate": {ipa:"ɹeɪt",ko:"요금"},
  "rather": {ipa:"ˈɹɑːðə",ko:"차라리"},
  "raw": {ipa:"ɹɔː",ko:"날것의"},
  "reach": {ipa:"ɹiːt͡ʃ",ko:"도달하다"},
  "reached": {ipa:"ɹiːtʃt",ko:"손을 뻗었다"},
  "reaching": {ipa:"ˈɹiːtʃɪŋ",ko:"다가가는"},
  "ready": {ipa:"ˈɹɛdi",ko:"준비된"},
  "real": {ipa:"ɹiːl",ko:"진짜의",pron:"[리]얼"},
  "really": {ipa:"ˈɹɪəli",ko:"정말"},
  "reason": {ipa:"ˈɹiːzən",ko:"까닭"},
  "reasonable": {ipa:"ˈɹiː.zən.ə.bəl",ko:"타당한"},
  "reasons": {ipa:"ˈɹiːzənz",ko:"까닭"},
  "reassuring": {ipa:"ˌriːəˈʃʊərɪŋ",ko:"안심시키는"},
  "receipt": {ipa:"ɹɪˈsiːt",ko:"영수증"},
  "receive": {ipa:"ɹɪˈsiːv",ko:"받다"},
  "recharge": {ipa:"ˈɹiːtʃɑː(ɹ)dʒ",ko:"충전하다"},
  "recline": {ipa:"ɹəˈklaɪn",ko:"뒤로 젖히다",pron:"리[클라]인"},
  "recognize": {ipa:"ˈɹɛkənaɪz",ko:"알아보다",pron:"[레]코그나이즈"},
  "recommend": {ipa:"ɹɛkəˈmɛnd",ko:"추천하다"},
  "recommendations": {ipa:"ˌɹekəmenˈdeɪʃənz",ko:"추천"},
  "reconsider": {ipa:"ˌɹiːkənˈsɪdə",ko:"다시 생각하다"},
  "record": {ipa:"ˈɹɛkɔːd",ko:"녹음하다"},
  "recover": {ipa:"ɹɪˈkʌvə",ko:"낫다"},
  "recovered": {ipa:"ɹɪˈkʌvəd",ko:"다 나은"},
  "reduce": {ipa:"ɹɪˈdjuːs",ko:"줄이다"},
  "refill": {ipa:"ˈɹiː.fɪl",ko:"리필"},
  "refrigerator": {ipa:"ɹɪˈfɹɪd͡ʒəˌɹeɪtə",ko:"냉장고"},
  "refund": {ipa:"ˈriːfʌnd",ko:"환불"},
  "refused": {ipa:"ɹɪˈfjuːzd",ko:"거절된"},
  "regards": {ipa:"ɹɪˈɡɑːdz",ko:"안부"},
  "regret": {ipa:"ɹiˈɡɹɛt",ko:"후회하다"},
  "regrets": {ipa:"rɪˈɡrets",ko:"후회"},
  "reheat": {ipa:"ˌɹiːˈhiːt",ko:"다시 데우다"},
  "reimbursement": {ipa:"ˌɹiːɪmˈbɜːsmənt",ko:"비용 보전"},
  "reissue": {ipa:"ˌɹiːˈɪʃuː",ko:"다시 발급하다"},
  "relate": {ipa:"ɹiˈleɪt",ko:"공감하다"},
  "relatives": {ipa:"ˈɹɛl.ə.tɪvz",ko:"친척"},
  "relax": {ipa:"ɹɪˈlæks",ko:"긴장을 풀다"},
  "relaxing": {ipa:"rɪˈlæksɪŋ",ko:"편안한"},
  "relief": {ipa:"ɹɪˈliːf",ko:"안도"},
  "reload": {ipa:"ˌɹiːˈləʊd",ko:"충전하다"},
  "rely": {ipa:"ɹɪˈlaɪ",ko:"의지하다"},
  "remarkable": {ipa:"ɹɪˈmɑːkəbl̩",ko:"놀라운"},
  "remember": {ipa:"ɹɪˈmɛmbə",ko:"기억하다"},
  "remote": {ipa:"[ɹəˈməʊt]",ko:"리모컨",pron:"리[모]트"},
  "remove": {ipa:"ɹɪˈmuːv",ko:"벗다, 없애다"},
  "rent": {ipa:"ɹɛnt",ko:"빌리다"},
  "repack": {ipa:"ˌɹiːˈpæk",ko:"다시 싸다"},
  "rephrase": {ipa:"ˌɹiːˈfɹeɪz",ko:"고쳐 말하다"},
  "replace": {ipa:"ɹɪˈpleɪs",ko:"바꿔주다"},
  "report": {ipa:"ɹɪˈpɔːt",ko:"신고하다"},
  "reporting": {ipa:"ɹɪˈpɔːtɪŋ",ko:"보고하는"},
  "request": {ipa:"ɹɪˈkwɛst",ko:"요청하다"},
  "requested": {ipa:"ɹɪˈkwɛstɪd",ko:"요청했다"},
  "required": {ipa:"ɹɪˈkwaɪəd",ko:"필요한"},
  "reservation": {ipa:"ˌɹɛzəˈveɪʃən",ko:"예약"},
  "reserve": {ipa:"ɹɪˈzɜːv",ko:"미리 잡아두다"},
  "reserved": {ipa:"ɹɪˈzɜːvd",ko:"예약된"},
  "resonates": {ipa:"ˈrezəneɪts",ko:"공감되다"},
  "responsibility": {ipa:"ɹɪˌspɑnsəˈbɪlɪɾi",ko:"책임",pron:"리스판서[빌리]티"},
  "rest": {ipa:"ɹɛst",ko:"휴식"},
  "restaurant": {ipa:"ˈɹɛs.t(ə).ɹ(ə)nt",ko:"식당",pron:"[레]스토랑"},
  "restroom": {ipa:"ˈrestruːm",ko:"화장실"},
  "result": {ipa:"ɹɪˈzʌlt",ko:"결과"},
  "retired": {ipa:"ɹɪˈtaɪəd",ko:"은퇴했다"},
  "return": {ipa:"ɹɪˈtɜːn",ko:"돌아오는, 반품하다"},
  "reunion": {ipa:"ɹiːˈjuːnjən",ko:"오랜만의 모임",pron:"리[유]니언"},
  "review": {ipa:"ɹɪˈvjuː",ko:"후기"},
  "ride": {ipa:"ɹaɪd",ko:"태워주기"},
  "ridiculous": {ipa:"ɹɪˈdɪkjʊləs",ko:"터무니없는"},
  "right": {ipa:"ˈɹaɪt",ko:"오른쪽, 맞는"},
  "risks": {ipa:"ɹɪsks",ko:"위험"},
  "risky": {ipa:"ˈɹɪski",ko:"위험한"},
  "roads": {ipa:"ɹəʊdz",ko:"길"},
  "role": {ipa:"ɹəʊl",ko:"역할"},
  "room": {ipa:"ɹuːm",ko:"방"},
  "rooms": {ipa:"ɹuːmz",ko:"방"},
  "rooting": {ipa:"ˈɹuːtɪŋ",ko:"응원하는"},
  "roundtrip": {ipa:"ˈraʊndtrɪp",ko:"왕복의"},
  "route": {ipa:"ɹuːt",ko:"경로"},
  "row": {ipa:"ˈɹəʊ",ko:"열"},
  "rumor": {ipa:"ˈɹuːmə",ko:"소문"},
  "rumour": {ipa:"ˈɹuːmə",ko:"소문"},
  "run": {ipa:"ɹʊn",ko:"다니다, 달리다",pron:"[런]"},
  "running": {ipa:"ˈɹʌnɪŋ",ko:"~하는 중"},
  "runs": {ipa:"ɹʌnz",ko:"이끈다"},
  "rush": {ipa:"ɹʌʃ",ko:"서두름"},
  "rushed": {ipa:"ɹʌʃt",ko:"성급했다"},
  "safe": {ipa:"seɪf",ko:"안전한, 금고"},
  "safely": {ipa:"ˈseɪfli",ko:"안전하게"},
  "sags": {ipa:"sæɡz",ko:"내려앉는다"},
  "said": {ipa:"sed",ko:"말했다"},
  "sale": {ipa:"seɪl",ko:"할인 판매"},
  "salt": {ipa:"sɔːlt",ko:"소금"},
  "salty": {ipa:"ˈsɔːlti",ko:"짠"},
  "same": {ipa:"seɪm",ko:"같은"},
  "sauce": {ipa:"sɔːs",ko:"소스"},
  "save": {ipa:"seɪv",ko:"맡아두다"},
  "saw": {ipa:"sɔː",ko:"봤다"},
  "say": {ipa:"seɪ",ko:"말하다"},
  "says": {ipa:"sez",ko:"말한다"},
  "scan": {ipa:"skæn",ko:"읽히다"},
  "scared": {ipa:"skɛəd",ko:"겁먹은"},
  "schedule": {ipa:"ˈskɛ.dʒu.əl",ko:"일정",pron:"[스케]줄"},
  "school": {ipa:"skuːl",ko:"학교"},
  "scoot": {ipa:"skuːt",ko:"옆으로 비키다"},
  "scratchy": {ipa:"ˈskɹætʃi",ko:"칼칼한"},
  "screen": {ipa:"skɹiːn",ko:"화면"},
  "search": {ipa:"sɜːt͡ʃ",ko:"살펴보다"},
  "season": {ipa:"ˈsiːzən",ko:"철"},
  "seat": {ipa:"siːt",ko:"자리"},
  "seatbelt": {ipa:"ˈsiːtbɛlt",ko:"안전벨트"},
  "seating": {ipa:"ˈsiːtɪŋ",ko:"좌석 배정"},
  "seats": {ipa:"siːts",ko:"자리"},
  "second": {ipa:"ˈsekənd",ko:"두 번째, 잠깐"},
  "security": {ipa:"sɪˈkjʊəɹəti",ko:"보안"},
  "see": {ipa:"siː",ko:"보다, 만나다"},
  "seeing": {ipa:"ˈsiːɪŋ",ko:"보는 것"},
  "seem": {ipa:"siːm",ko:"~인 것 같다"},
  "seems": {ipa:"siːmz",ko:"~해 보이다"},
  "seen": {ipa:"ˈsiːn",ko:"봤다"},
  "send": {ipa:"sɛnd",ko:"보내다"},
  "senior": {ipa:"ˈsiːniə",ko:"윗사람의"},
  "sense": {ipa:"sɛn(t)s",ko:"뜻, 이치",pron:"[센]스"},
  "sensitive": {ipa:"ˈsɛnsɪtɪv",ko:"예민한"},
  "sent": {ipa:"sɛnt",ko:"보냈다"},
  "seoul": {ipa:"səʊl",ko:"서울",pron:"[서]울"},
  "separate": {ipa:"ˈsɛpəɹət",ko:"따로 된"},
  "separately": {ipa:"ˈseprətli",ko:"따로"},
  "serious": {ipa:"ˈsɪə.ɹi.əs",ko:"진지한"},
  "served": {ipa:"sɜːvd",ko:"제공되는"},
  "service": {ipa:"ˈsɜːvɪs",ko:"서비스"},
  "serving": {ipa:"ˈsɜːvɪŋ",ko:"1인분"},
  "set": {ipa:"sɛt",ko:"마련하다, 다 된"},
  "seven": {ipa:"ˈsɛv.ən"},
  "shade": {ipa:"ʃeɪd",ko:"덮개"},
  "shame": {ipa:"ʃeɪm",ko:"아쉬움"},
  "shampoo": {ipa:"ʃæmˈpuː",ko:"샴푸",pron:"샴[푸]"},
  "share": {ipa:"ʃɛə",ko:"나누다"},
  "shared": {ipa:"ˈʃɛə(ɹ)d",ko:"함께 쓰는"},
  "she": {ipa:"ʃiː"},
  "she's": {ipa:"ʃiːz"},
  "sheets": {ipa:"ʃiːts",ko:"침대 시트"},
  "shift": {ipa:"ʃɪft",ko:"옮기다"},
  "ship": {ipa:"ʃɪp",ko:"부치다"},
  "shipping": {ipa:"ˈʃɪpɪŋ",ko:"배송"},
  "shocked": {ipa:"ʃɒkt",ko:"크게 놀란"},
  "shoes": {ipa:"ʃuːz",ko:"신발"},
  "shop": {ipa:"ʃɒp",ko:"가게"},
  "short": {ipa:"ʃɔːt",ko:"짧은, 모자란"},
  "shorter": {ipa:"ˈʃɔːtə",ko:"더 짧은"},
  "shortly": {ipa:"ˈʃɔːtli",ko:"곧"},
  "shot": {ipa:"ʃɒt",ko:"시도",pron:"[샷]"},
  "should": {ipa:"ʃʊd"},
  "show": {ipa:"ʃəʊ",ko:"보여주다"},
  "showed": {ipa:"ʃəʊd",ko:"나타났다"},
  "shower": {ipa:"ˈʃaʊ.ə(ɹ)",ko:"샤워",pron:"[샤]워"},
  "showing": {ipa:"ˈʃəʊɪŋ",ko:"보여주는"},
  "shut": {ipa:"ʃʌt",ko:"닫다"},
  "shuttle": {ipa:"ˈʃʌtl",ko:"셔틀"},
  "shy": {ipa:"ʃaɪ",ko:"낯을 가리는"},
  "siblings": {ipa:"ˈsɪblɪŋz",ko:"형제자매"},
  "sick": {ipa:"sɪk",ko:"아픈"},
  "side": {ipa:"saɪd",ko:"옆, 곁들이"},
  "sideways": {ipa:"ˈsaɪdweɪz",ko:"가로로"},
  "sign": {ipa:"saɪn",ko:"서명하다"},
  "sim": {ipa:"sɪm",ko:"유심"},
  "similar": {ipa:"ˈsɪmələ",ko:"비슷한"},
  "simply": {ipa:"ˈsɪmpli",ko:"쉽게"},
  "since": {ipa:"sɪns",ko:"~한 이후로"},
  "sink": {ipa:"sɪŋk",ko:"세면대"},
  "sister": {ipa:"ˈsɪstə",ko:"누나, 언니, 여동생"},
  "sit": {ipa:"sɪt",ko:"앉다"},
  "sits": {ipa:"sɪts",ko:"앉다, 받아들여지다"},
  "situation": {ipa:"sɪtjuːˈeɪʃən",ko:"상황"},
  "size": {ipa:"saɪz",ko:"크기"},
  "skeptical": {ipa:"ˈskeptɪkəl",ko:"회의적인"},
  "sleep": {ipa:"sliːp",ko:"잠",pron:"[슬립]"},
  "sleeps": {ipa:"sliːps",ko:"잔다",pron:"[슬립]스"},
  "slept": {ipa:"slept",ko:"잤다"},
  "slipped": {ipa:"slɪpt",ko:"미끄러졌다, 깜빡했다"},
  "slippery": {ipa:"ˈslɪpəɹi",ko:"미끄러운"},
  "slowly": {ipa:"ˈsləʊli",ko:"천천히"},
  "small": {ipa:"smɔːl",ko:"작은"},
  "smaller": {ipa:"ˈsmɑlɚ",ko:"더 작은",pron:"[스몰]러"},
  "smallest": {ipa:"ˈsmɔːlɪst",ko:"가장 작은"},
  "smell": {ipa:"smɛl",ko:"냄새 맡다"},
  "smells": {ipa:"smɛlz",ko:"냄새가 나다"},
  "smile": {ipa:"smaɪl",ko:"웃는 얼굴"},
  "smoke": {ipa:"sməʊk",ko:"담배 연기"},
  "smooth": {ipa:"smuːð",ko:"순조로운"},
  "snow": {ipa:"snəʊ",ko:"눈이 오다",pron:"[스노]우"},
  "so": {ipa:"səʊ"},
  "soap": {ipa:"səʊp",ko:"비누"},
  "soccer": {ipa:"ˈsɒkə",ko:"축구",pron:"[사]커"},
  "sold": {ipa:"ˈsəʊld",ko:"납득된, 팔린"},
  "solid": {ipa:"ˈsɒlɪd",ko:"부탁, 단단한"},
  "solved": {ipa:"sɒlvd",ko:"풀었다"},
  "solves": {ipa:"sɒlvz",ko:"풀어준다"},
  "some": {ipa:"sʌm"},
  "somebody": {ipa:"ˈsʌmbədi"},
  "someday": {ipa:"ˈsʌmdeɪ",ko:"언젠가"},
  "someone": {ipa:"ˈsʌmwʌn"},
  "something": {ipa:"ˈsʌmθɪŋ",ko:"무언가"},
  "something's": {ipa:"ˈsʌmθɪŋz"},
  "sometime": {ipa:"ˈsʌmˌtaɪm",ko:"언젠가"},
  "somewhere": {ipa:"ˈsʌm.hweːɹ"},
  "son": {ipa:"sʌn",ko:"아들"},
  "sons": {ipa:"sʌnz",ko:"아들들"},
  "soon": {ipa:"suːn",ko:"곧"},
  "sooner": {ipa:"ˈsuːnə",ko:"더 일찍"},
  "sore": {ipa:"sɔːɹ",ko:"아픈"},
  "sorry": {ipa:"ˈsɔɹi",ko:"미안한, 유감스러운",pron:"[쏘]리"},
  "sounds": {ipa:"saʊndz",ko:"~처럼 들리다"},
  "soy": {ipa:"sɔɪ",ko:"콩"},
  "space": {ipa:"speɪs",ko:"공간"},
  "spare": {ipa:"ˈspɛə(ɹ)",ko:"여분의"},
  "speak": {ipa:"spiːk",ko:"말하다"},
  "speaks": {ipa:"spiːks",ko:"말한다"},
  "special": {ipa:"ˈspɛ.ʃəl",ko:"오늘의 요리, 특별한"},
  "speechless": {ipa:"ˈspiːtʃ.lɪs",ko:"말문이 막힌",pron:"[스피]치리스"},
  "speed": {ipa:"spiːd",ko:"속도를 내다"},
  "spell": {ipa:"spɛl",ko:"철자를 말하다"},
  "spicy": {ipa:"ˈspaɪsi",ko:"매운"},
  "split": {ipa:"splɪt",ko:"나누다"},
  "spoke": {ipa:"spəʊk",ko:"말했다"},
  "spot": {ipa:"spɑt",ko:"자리"},
  "spots": {ipa:"spɒts",ko:"가볼 만한 곳"},
  "spring": {ipa:"spɹɪŋ",ko:"봄"},
  "squeeze": {ipa:"skwiːz",ko:"비집고 지나가다"},
  "staff": {ipa:"ˈstæf",ko:"직원"},
  "stand": {ipa:"stænd",ko:"서다"},
  "start": {ipa:"stɑːt",ko:"시작하다"},
  "started": {ipa:"ˈstɑːtɪd",ko:"시작했다"},
  "station": {ipa:"ˈsteɪʃən",ko:"역"},
  "stay": {ipa:"steɪ",ko:"머물다, 유지하다"},
  "stayed": {ipa:"steːd",ko:"머물렀다"},
  "staying": {ipa:"ˈsteɪ.ɪŋ",ko:"머무는"},
  "stays": {ipa:"steɪz",ko:"머물다"},
  "stead": {ipa:"stɛd",ko:"대신"},
  "steady": {ipa:"ˈstɛdi",ko:"흔들리지 않게"},
  "step": {ipa:"stɛp",ko:"발을 옮기다"},
  "stick": {ipa:"stɪk",ko:"끝까지 하다"},
  "stifling": {ipa:"ˈstaɪflɪŋ",ko:"숨 막히는"},
  "still": {ipa:"stɪl"},
  "stock": {ipa:"stɒk",ko:"재고"},
  "stop": {ipa:"stɒp",ko:"정류장, 멈추다"},
  "stopover": {ipa:"ˈstɒpoʊvə",ko:"경유"},
  "stops": {ipa:"stɑps",ko:"정거장",pron:"[스톱]스"},
  "storage": {ipa:"ˈstɔ.ɹɪd͡ʒ",ko:"보관"},
  "store": {ipa:"stɔːɹ",ko:"가게, 보관하다"},
  "stow": {ipa:"stəʊ",ko:"제자리에 넣다"},
  "straight": {ipa:"stɹeɪt",ko:"곧장"},
  "strange": {ipa:"ˈstɹeɪnd͡ʒ",ko:"이상한"},
  "straw": {ipa:"stɹɔː",ko:"빨대"},
  "street": {ipa:"stɹiːt",ko:"거리"},
  "stress": {ipa:"stɹes",ko:"스트레스"},
  "stretch": {ipa:"stɹɛtʃ",ko:"무리"},
  "stroller": {ipa:"ˈstɹəʊlə",ko:"유모차"},
  "strong": {ipa:"stɹɑŋ",ko:"강한",pron:"[스트롱]"},
  "stuffy": {ipa:"ˈstʌfi",ko:"공기가 탁한"},
  "subject": {ipa:"ˈsʌb.dʒɪkt",ko:"화제",pron:"[서]브젝트"},
  "subway": {ipa:"ˈsʌbˌweɪ",ko:"지하철"},
  "such": {ipa:"sʌt͡ʃ"},
  "suggest": {ipa:"səˈdʒɛst",ko:"제안하다"},
  "suitcase": {ipa:"ˈsuːtkeɪs",ko:"여행 가방"},
  "suitcases": {ipa:"ˈsuːtkeɪsɪz",ko:"여행 가방"},
  "suits": {ipa:"suːts",ko:"어울린다"},
  "sum": {ipa:"sʌm"},
  "summer's": {ipa:"ˈsʌməz"},
  "supervisor": {ipa:"ˈsuːpɚˌvaɪzɚ",ko:"관리자",pron:"[슈]퍼바이저"},
  "sure": {ipa:"ʃʊə",ko:"확실한"},
  "surprised": {ipa:"səˈpɹaɪzd",ko:"놀란"},
  "swamped": {ipa:"swɒmpt",ko:"일이 밀린"},
  "swapping": {ipa:"ˈswɒpɪŋ",ko:"맞바꾸는"},
  "sweet": {ipa:"swiːt",ko:"다정한"},
  "switch": {ipa:"swɪtʃ",ko:"바꾸다"},
  "switched": {ipa:"swɪtʃt",ko:"바꿨다"},
  "switching": {ipa:"ˈswɪtʃɪŋ",ko:"바꾸는"},
  "table": {ipa:"ˈteɪbəl",ko:"자리, 탁자"},
  "tables": {ipa:"ˈteɪbl̩z",ko:"자리",pron:"[테이]블즈"},
  "tag": {ipa:"tæɡ",ko:"꼬리표"},
  "take": {ipa:"teɪk",ko:"가져가다, 걸리다"},
  "takeaway": {ipa:"ˈteɪkəweɪ",ko:"포장"},
  "taken": {ipa:"ˈteɪkən",ko:"자리가 찬"},
  "takeoff": {ipa:"ˈteɪkɒf",ko:"이륙",pron:"[테이]크오프"},
  "takes": {ipa:"teɪks",ko:"덜어준다"},
  "taking": {ipa:"ˈteɪkɪŋ",ko:"찍는, 가져가는"},
  "talk": {ipa:"toːk",ko:"이야기하다"},
  "talked": {ipa:"tɔːkt",ko:"이야기했다"},
  "taller": {ipa:"ˈtɔːlə",ko:"키가 더 큰"},
  "tap": {ipa:"tæp",ko:"카드를 대다"},
  "tax": {ipa:"tæks",ko:"세금"},
  "taxi": {ipa:"ˈtæk.si",ko:"택시"},
  "tea": {ipa:"tiː",ko:"차"},
  "teach": {ipa:"tiːt͡ʃ",ko:"가르치다"},
  "team": {ipa:"tiːm",ko:"팀"},
  "teenager": {ipa:"ˈtiːneɪdʒə",ko:"십 대",pron:"[틴]에이저"},
  "tell": {ipa:"tɛl",ko:"말하다"},
  "ten": {ipa:"ten"},
  "tend": {ipa:"tɛnd",ko:"~하는 편이다"},
  "terminal": {ipa:"ˈtɜːmɪnəl",ko:"터미널"},
  "terrible": {ipa:"ˈtɛ.ɹə.bl̩",ko:"끔찍한"},
  "terrified": {ipa:"ˈtɛɹɪfaɪd",ko:"몹시 두려운"},
  "text": {ipa:"tɛkst",ko:"문자를 보내다"},
  "than": {ipa:"ðæn"},
  "thank": {ipa:"[θaŋk]",ko:"고마워하다",pron:"[쌩]크"},
  "thankful": {ipa:"ˈθæŋkfəl",ko:"고마워하는",pron:"[쌩]크풀"},
  "thanks": {ipa:"θæŋks",ko:"고맙습니다",pron:"[쌩]크스"},
  "that": {ipa:"ˈðæt"},
  "that's": {ipa:"ðæts"},
  "the": {ipa:"ðə"},
  "their": {ipa:"ðeə"},
  "them": {ipa:"ðem"},
  "themselves": {ipa:"ðəmˈsɛlvz"},
  "then": {ipa:"ðen"},
  "there": {ipa:"ðeə"},
  "there's": {ipa:"ðeəz"},
  "these": {ipa:"ðiːz"},
  "they": {ipa:"ðeɪ"},
  "they're": {ipa:"ðeə"},
  "they've": {ipa:"ðeɪv"},
  "thin": {ipa:"θɪn",ko:"얇은"},
  "thing": {ipa:"θɪŋ",ko:"것"},
  "things": {ipa:"θɪŋz",ko:"것들"},
  "think": {ipa:"θɪŋk",ko:"생각하다"},
  "thinking": {ipa:"ˈθɪŋkɪŋ",ko:"생각하는"},
  "this": {ipa:"ðɪs"},
  "those": {ipa:"ðəʊz"},
  "thought": {ipa:"θɔːt",ko:"생각했다"},
  "thoughts": {ipa:"θɑts",ko:"생각",pron:"[쏘]츠"},
  "thousand": {ipa:"ˈθaʊzənd"},
  "three": {ipa:"θɹiː",pron:"[쓰리]"},
  "throat": {ipa:"ˈθɹəʊt",ko:"목"},
  "through": {ipa:"θɹuː"},
  "throw": {ipa:"θɹəʊ",ko:"던지다"},
  "ticket": {ipa:"ˈtɪkɪt",ko:"표",pron:"[티]켓"},
  "ticks": {ipa:"tɪks",ko:"짜증나게 한다"},
  "tidy": {ipa:"ˈtaɪdi",ko:"정돈하다"},
  "tight": {ipa:"taɪt",ko:"꽉 끼는"},
  "time": {ipa:"taɪm",ko:"시간"},
  "tip": {ipa:"tɪp",ko:"팁"},
  "to": {ipa:"tuː"},
  "to-go": {ipa:"tə ˈɡoʊ",ko:"포장용",pron:"투[고]"},
  "today": {ipa:"təˈdeɪ",ko:"오늘",pron:"투[데이]"},
  "today's": {ipa:"təˈdeɪz",pron:"투[데이]즈"},
  "together": {ipa:"təˈɡɛð.ə(ɹ)",ko:"함께",pron:"투[게]더"},
  "togo": {ipa:"tə ˈɡoʊ",ko:"포장용",pron:"투[고]"},
  "toilet": {ipa:"ˈtɔɪ.lət",ko:"변기",pron:"[토]일렛"},
  "told": {ipa:"təʊld",ko:"말해 줬다"},
  "tonight": {ipa:"təˈnaɪt",ko:"오늘 밤",pron:"투[나이]트"},
  "too": {ipa:"tuː"},
  "took": {ipa:"tʊk",ko:"넘겨받았다, 가져갔다"},
  "toothbrush": {ipa:"ˈtuːθbɹʌʃ",ko:"칫솔"},
  "torn": {ipa:"tɔːn",ko:"마음이 갈린"},
  "total": {ipa:"ˈtəʊ.təl",ko:"완전한"},
  "totally": {ipa:"ˈtoʊt.əl.i",ko:"완전히"},
  "touch": {ipa:"tʌtʃ",ko:"연락, 만지다"},
  "touched": {ipa:"tʌt͡ʃt",ko:"감동한"},
  "tougher": {ipa:"ˈtʌfə",ko:"더 힘든"},
  "towels": {ipa:"ˈtaʊəlz",ko:"수건",pron:"[타]월즈"},
  "town": {ipa:"taʊn",ko:"동네"},
  "trading": {ipa:"ˈtreɪdɪŋ",ko:"맞바꾸는"},
  "traffic": {ipa:"ˈtɹæfɪk",ko:"교통, 차량 흐름"},
  "train": {ipa:"tɹeɪn",ko:"기차"},
  "transfer": {ipa:"ˈtɹænzfɜː",ko:"환승하다",pron:"[트랜]스퍼"},
  "transformer": {ipa:"tɹænsˈfɔːmə",ko:"변압기"},
  "transit": {ipa:"ˈtɹæn.sɪt",ko:"환승"},
  "trash": {ipa:"tɹæʃ",ko:"쓰레기"},
  "travel": {ipa:"ˈtɹævəl",ko:"여행",pron:"[트래]블"},
  "traveling": {ipa:"ˈtɹæv.l̩iŋ",ko:"여행 중인",pron:"[트래]블링"},
  "tray": {ipa:"tɹeɪ",ko:"쟁반"},
  "trip": {ipa:"tɹɪp",ko:"여행"},
  "trolley": {ipa:"ˈtrɒli",ko:"짐 수레"},
  "trouble": {ipa:"ˈtɹʌb(ə)l",ko:"번거로움"},
  "troubling": {ipa:"ˈtɹʌb(ə)lɪŋ",ko:"성가시게 하는",pron:"[트러]블링"},
  "trunk": {ipa:"tɹʌŋk",ko:"트렁크"},
  "try": {ipa:"tɹaɪ",ko:"해보다"},
  "trying": {ipa:"ˈtɹaɪ.ɪŋ",ko:"애쓰는"},
  "turbulence": {ipa:"ˈtɜːbjələns",ko:"난기류",pron:"[터]뷸런스"},
  "turn": {ipa:"tɜːn",ko:"돌다, 켜다"},
  "turned": {ipa:"tɜːnd",ko:"(나이가) 되었다"},
  "turning": {ipa:"ˈtɜːnɪŋ",ko:"켜지는"},
  "tv": {ipa:"ˌtiːˈviː",ko:"티브이"},
  "twins": {ipa:"twɪnz",ko:"쌍둥이"},
  "two": {ipa:"tuː"},
  "type": {ipa:"taɪp",pron:"[타입]"},
  "u-turn": {ipa:"ˈjuːtɜːn",ko:"유턴"},
  "umbrella": {ipa:"ʌmˈbrelə",ko:"우산"},
  "unbelievable": {ipa:"ˌʌnbəˈliːvəbl̩",ko:"믿기 힘든"},
  "uncle": {ipa:"ˈʌŋkəl",ko:"삼촌"},
  "uncomfortable": {ipa:"ʌnˈkʌmftəbəl",ko:"불편한"},
  "under": {ipa:"ˈʌndə"},
  "undercooked": {ipa:"ˌʌndəˈkʊkt",ko:"덜 익은"},
  "underground": {ipa:"ˈʌndəɡɹaʊnd",ko:"지하철"},
  "understand": {ipa:"ˌʌndəˈstænd",ko:"이해하다"},
  "understanding": {ipa:"ʌndəˈstandɪŋ",ko:"이해해 주는 것",pron:"언더[스탠]딩"},
  "unfair": {ipa:"ʌnˈfɛə(ɹ)",ko:"불공평한"},
  "unpredictable": {ipa:"ˌʌnprɪˈdɪktəbl",ko:"종잡을 수 없는"},
  "until": {ipa:"ənˈtɪl",ko:"~까지"},
  "up": {ipa:"ʌp"},
  "upgrade": {ipa:"ˈʌp.ɡɹeɪd",ko:"등급을 올리다"},
  "upright": {ipa:"ˈʌpɹaɪt",ko:"똑바로 세운",pron:"[업]라이트"},
  "upset": {ipa:"ʌpˈset",ko:"속상한"},
  "upstairs": {ipa:"ˈʌpˌstɛəz",ko:"위층으로"},
  "urgent": {ipa:"ˈɜːdʒənt",ko:"급한"},
  "us": {ipa:"əs"},
  "use": {ipa:"juːz",ko:"쓰다"},
  "usual": {ipa:"ˈjuːʒʊəl",ko:"평소",pron:"[유]주얼"},
  "uturn": {ipa:"ˈjuːtɜːn",ko:"유턴"},
  "vacant": {ipa:"ˈveɪkənt",ko:"비어 있는"},
  "vacation": {ipa:"veɪˈkeɪʃ(ə)n",ko:"휴가"},
  "validate": {ipa:"ˈvælɪdeɪt",ko:"확인 도장을 찍다"},
  "valuables": {ipa:"ˈvæljuəbəlz",ko:"귀중품",pron:"[밸]류어블즈"},
  "vegan": {ipa:"ˈviːɡən",ko:"완전 채식의",pron:"[비]건"},
  "vegetarian": {ipa:"vɛd͡ʒɪˈtɛəɹi.ən",ko:"채식주의자",pron:"베지[테]리언"},
  "ventilation": {ipa:"ˌventɪˈleɪʃən",ko:"환기"},
  "verify": {ipa:"ˈverɪfaɪ",ko:"확인하다"},
  "very": {ipa:"ˈvɛɹi"},
  "video": {ipa:"ˈvɪ.di.əʊ",ko:"영상"},
  "view": {ipa:"vjuː",ko:"전망"},
  "visa": {ipa:"ˈviːzə",ko:"비자",pron:"[비]자"},
  "visit": {ipa:"ˈvɪzɪt",ko:"방문"},
  "visiting": {ipa:"ˈvɪzɪtɪŋ",ko:"방문하는"},
  "visitors": {ipa:"ˈvɪzɪtəz",ko:"방문객"},
  "voice": {ipa:"vɔɪs",ko:"목소리"},
  "volume": {ipa:"ˈvɒl.juːm",ko:"음량"},
  "voucher": {ipa:"ˈvaʊtʃə(ɹ)",ko:"교환권"},
  "wait": {ipa:"weɪt",ko:"기다리다, 대기"},
  "waiting": {ipa:"ˈweɪtɪŋ",ko:"기다리는"},
  "wake-up": {ipa:"ˈweɪk ʌp",ko:"모닝콜의"},
  "wakeup": {ipa:"ˈweɪk ʌp",ko:"모닝콜의"},
  "walking": {ipa:"ˈwɔːkɪŋ",ko:"걷는"},
  "wall": {ipa:"wɔːl",ko:"벽"},
  "want": {ipa:"wɔnt",ko:"원하다"},
  "warm": {ipa:"wɔːm",ko:"따뜻한"},
  "warranty": {ipa:"ˈwɒɹənti",ko:"보증"},
  "was": {ipa:"wɒz"},
  "washable": {ipa:"ˈwɒʃəbəl",ko:"빨 수 있는"},
  "washing": {ipa:"ˈwɒʃɪŋ",ko:"빨래하는"},
  "watch": {ipa:"wɒt͡ʃ",ko:"지켜보다"},
  "watched": {ipa:"wɒtʃt",ko:"봤다"},
  "watches": {ipa:"ˈwɒt͡ʃɪz",ko:"봐준다"},
  "watching": {ipa:"ˈwɒtʃɪŋ",ko:"보는"},
  "water": {ipa:"ˈwɔːtə",ko:"물"},
  "wavelength": {ipa:"ˈweɪvlɛŋ(k)θ",ko:"생각의 결",pron:"[웨이]블렝쓰"},
  "way": {ipa:"weɪ",ko:"길, 방식"},
  "we": {ipa:"wiː"},
  "we'd": {ipa:"wiːd"},
  "we'll": {ipa:"wiːl"},
  "we're": {ipa:"wɪə"},
  "we've": {ipa:"wiːv"},
  "weak": {ipa:"wiːk",ko:"약한"},
  "wear": {ipa:"wɛə",ko:"매다, 입다"},
  "weather": {ipa:"ˈwɛðə",ko:"날씨"},
  "weather's": {ipa:"ˈweðəz"},
  "wedding": {ipa:"ˈwɛdɪŋ",ko:"결혼식"},
  "week": {ipa:"wiːk",ko:"주"},
  "weekend": {ipa:"wiːˈkɛnd",ko:"주말"},
  "weeks": {ipa:"wiːks",ko:"주"},
  "weigh": {ipa:"weɪ",ko:"무게가 나가다"},
  "weight": {ipa:"weɪt",ko:"무게"},
  "welcome": {ipa:"ˈwɛlkəm",ko:"천만에요"},
  "well": {ipa:"wɛl",ko:"잘"},
  "went": {ipa:"wɛnt",ko:"갔다"},
  "were": {ipa:"wɜː"},
  "what": {ipa:"wɒt",pron:"[왓]"},
  "what's": {ipa:"wɒts",pron:"[왓]츠"},
  "wheelchair": {ipa:"ˈwiːltʃeə",ko:"휠체어"},
  "when": {ipa:"ʍɛn"},
  "whenever": {ipa:"wəˈnɛvə",ko:"언제든",pron:"웬[에]버"},
  "where": {ipa:"wɛə(ɹ)"},
  "where's": {ipa:"weəz"},
  "which": {ipa:"wɪt͡ʃ"},
  "while": {ipa:"waɪl"},
  "who": {ipa:"huː"},
  "whole": {ipa:"həʊl"},
  "wi-fi": {ipa:"ˈwaɪfaɪ",ko:"와이파이"},
  "wife": {ipa:"waɪf",ko:"아내"},
  "wifi": {ipa:"ˈwaɪfaɪ",ko:"와이파이"},
  "will": {ipa:"wɪl"},
  "window": {ipa:"ˈwɪndəʊ",ko:"창문, 창가"},
  "windy": {ipa:"ˈwɪndi",ko:"바람 부는"},
  "wish": {ipa:"wɪʃ",ko:"바라다"},
  "wishes": {ipa:"ˈwɪʃɪz",ko:"기원"},
  "with": {ipa:"wɪð"},
  "within": {ipa:"wɪˈθɪn",ko:"~이내에"},
  "woman": {ipa:"ˈwʊmən",ko:"여자",pron:"[우]먼"},
  "women": {ipa:"ˈwɪmɪn",ko:"여자들"},
  "won": {ipa:"wʌn",ko:"이겼다"},
  "won't": {ipa:"wəʊnt"},
  "wonderful": {ipa:"ˈwʌn.də.fl",ko:"훌륭한",pron:"[원]더풀"},
  "wondering": {ipa:"ˈwʌndəɹɪŋ",ko:"궁금해하는"},
  "word": {ipa:"wɜːd",ko:"말, 단어"},
  "words": {ipa:"wɜːdz",ko:"말"},
  "work": {ipa:"wɜːk",ko:"작동하다, 일하다"},
  "worked": {ipa:"wɜːkt",ko:"잘 풀렸다"},
  "working": {ipa:"ˈwɜːkɪŋ",ko:"작동하는"},
  "works": {ipa:"wɜːks",ko:"괜찮다, 작동하다"},
  "worn": {ipa:"wɔːn",ko:"지친"},
  "worried": {ipa:"ˈwʌɹid",ko:"걱정하는"},
  "worry": {ipa:"ˈwɒɹi",ko:"걱정하다"},
  "worth": {ipa:"wɜːθ",ko:"~할 가치가 있는"},
  "would": {ipa:"wʊd"},
  "wrap": {ipa:"ɹæp",ko:"포장하다"},
  "write": {ipa:"ɹaɪt",ko:"쓰다"},
  "wrong": {ipa:"ɹɒŋ",ko:"잘못된"},
  "year": {ipa:"jɪə",ko:"해, 년"},
  "years": {ipa:"jɪəz",ko:"해, 년"},
  "yes": {ipa:"jɛs"},
  "yet": {ipa:"jɛt"},
  "you": {ipa:"juː"},
  "you'll": {ipa:"juːl"},
  "you're": {ipa:"jʊəɹ"},
  "you've": {ipa:"juːv"},
  "young": {ipa:"jʌŋ",ko:"젊은"},
  "younger": {ipa:"ˈjʌŋɡə",ko:"나이가 더 적은"},
  "youngest": {ipa:"ˈjʌŋɡəst",ko:"가장 어린"},
  "your": {ipa:"jʊəɹ"},
  "yourself": {ipa:"jʊəˈself"},
  "zone": {ipa:"zəʊn"}
};
