// 단어별 발음 기호와 뜻. index.html이 채점 결과에서 씁니다.
//
// ipa  발음 기호. 사전 API(dictionaryapi.dev)에서 받아 왔습니다.
//      사전에 없는 단어는 이 항목이 없고, 그 자리는 비워서 보여줍니다.
// ko   한국어 뜻. 기능어(the, to, you 등)에는 달지 않았습니다.
//
// 한글 발음은 이 파일에 담지 않습니다. index.html의 변환기가 ipa로 그때그때 만듭니다.

const WORDS = {
  "a": {ipa:"ə"},
  "aback": {ipa:"əˈbæk",ko:"깜짝 놀라"},
  "about": {ipa:"əˈbaʊt"},
  "absurd": {ipa:"əbˈsɜːd",ko:"터무니없는"},
  "accept": {ipa:"ækˈsɛpt",ko:"받아들이다"},
  "across": {ipa:"əˈkɹɑs",ko:"가로질러"},
  "adapter": {ipa:"əˈdæptə",ko:"어댑터"},
  "adaptor": {ipa:"əˈdæptə",ko:"어댑터"},
  "additional": {ipa:"əˈdɪʃənəl",ko:"추가의"},
  "address": {ipa:"æˈdɹɛs",ko:"주소"},
  "adorable": {ipa:"əˈdɔːɹəbəl",ko:"사랑스러운"},
  "afraid": {ipa:"əˈfɹeɪd",ko:"두려운, 유감스러운"},
  "again": {ipa:"əˈɡeɪn"},
  "against": {ipa:"əˈɡeɪnst",ko:"반대하여"},
  "ages": {ipa:"ˈeɪ.dʒɪz",ko:"오랜 시간"},
  "agree": {ipa:"əˈɡɹi",ko:"동의하다"},
  "ahead": {ipa:"əˈhɛd",ko:"앞으로"},
  "air": {ipa:"ˈɛə",ko:"공기"},
  "airport": {ipa:"ˈɛə.pɔːt",ko:"공항"},
  "airsick": {ipa:"ˈeəsɪk",ko:"비행기 멀미가 나는"},
  "aisle": {ipa:"aɪl",ko:"통로"},
  "all": {ipa:"ɔːl"},
  "allergic": {ipa:"əˈlɜːdʒɪk",ko:"알레르기가 있는"},
  "allowance": {ipa:"əˈlaʊəns",ko:"허용량"},
  "allowed": {ipa:"əˈlaʊd",ko:"허용된"},
  "already": {ipa:"ɔːlˈɹedi"},
  "alright": {ipa:"ɒˈɹaɪt",ko:"괜찮은"},
  "am": {ipa:"æm"},
  "amazing": {ipa:"əˈmeɪzɪŋ",ko:"놀라운"},
  "an": {ipa:"æn"},
  "and": {ipa:"ænd"},
  "annoying": {ipa:"əˈnɔɪɪŋ",ko:"짜증나는"},
  "another": {ipa:"əˈnʌðə"},
  "anxious": {ipa:"ˈaŋ(k)ʃəs",ko:"불안한"},
  "any": {ipa:"ˈæni"},
  "anything": {ipa:"ˈɛ.nə.θɪŋ",ko:"무엇이든"},
  "anytime": {ipa:"ˈeniˌtaɪm",ko:"언제든"},
  "appreciate": {ipa:"əˈpɹiː.si.eɪt",ko:"고맙게 여기다"},
  "approved": {ipa:"əˈpɹuːvd",ko:"승인된"},
  "are": {ipa:"ɑː"},
  "area": {ipa:"ˈeəɹɪə",ko:"지역"},
  "arms": {ipa:"ɑːmz",ko:"팔"},
  "around": {ipa:"əˈɹaʊnd",ko:"주변에, 즈음"},
  "arrange": {ipa:"əˈɹeɪndʒ",ko:"마련하다"},
  "arrival": {ipa:"əˈɹaɪ.vəl",ko:"도착"},
  "arrived": {ipa:"əˈɹaɪvd",ko:"도착했다"},
  "as": {ipa:"æz"},
  "aside": {ipa:"əˈsaɪd",ko:"옆으로"},
  "ask": {ipa:"ɑːsk",ko:"묻다, 부탁하다"},
  "asking": {ipa:"ˈɑːskɪŋ",ko:"묻는 것"},
  "at": {ipa:"æt"},
  "available": {ipa:"əˈveɪləb(ə)l",ko:"이용 가능한"},
  "away": {ipa:"əˈweɪ"},
  "awful": {ipa:"ˈɔːfəl",ko:"끔찍한"},
  "awkward": {ipa:"ˈɔːkwəd",ko:"어색한"},
  "back": {ipa:"bæk"},
  "bad": {ipa:"bæd",ko:"나쁜"},
  "bag": {ipa:"bæɡ",ko:"가방, 봉투"},
  "baggage": {ipa:"ˈbæɡɪdʒ",ko:"수하물"},
  "bags": {ipa:"bæɡz",ko:"짐"},
  "bathroom": {ipa:"ˈbɑːθruːm",ko:"화장실"},
  "be": {ipa:"biː"},
  "bear": {ipa:"bɛə(ɹ)",ko:"참다, 견디다"},
  "beautiful": {ipa:"ˈbjuːtɪfəl",ko:"아름다운"},
  "bedding": {ipa:"ˈbɛdɪŋ",ko:"침구"},
  "beds": {ipa:"bɛdz",ko:"침대"},
  "been": {ipa:"biːn"},
  "begin": {ipa:"biˈɡɪn",ko:"시작하다"},
  "begun": {ipa:"bɪˈɡʌn",ko:"시작된"},
  "behind": {ipa:"bəˈhaɪnd",ko:"뒤에"},
  "believe": {ipa:"bɪˈliːv",ko:"믿다"},
  "belt": {ipa:"bɛlt",ko:"벨트"},
  "best": {ipa:"ˈbɛst",ko:"최고의"},
  "better": {ipa:"ˈbetə",ko:"더 좋은"},
  "between": {ipa:"bɪˈtwiːn"},
  "big": {ipa:"bɪɡ",ko:"큰"},
  "bigger": {ipa:"ˈbɪɡə",ko:"더 큰"},
  "bill": {ipa:"bɪl",ko:"청구서, 계산서"},
  "bin": {ipa:"bɪn",ko:"짐칸, 통"},
  "birthday": {ipa:"ˈbɜːθ.deɪ",ko:"생일"},
  "bit": {ipa:"bɪt",ko:"조금"},
  "bite": {ipa:"baɪt",ko:"한 입"},
  "blanket": {ipa:"ˈblæŋkɪt",ko:"담요"},
  "blocked": {ipa:"blɒkt",ko:"막힌"},
  "blocks": {ipa:"blɒks",ko:"블록, 구역"},
  "board": {ipa:"bɔːd",ko:"탑승하다"},
  "boarding": {ipa:"ˈbɔːdɪŋ",ko:"탑승"},
  "book": {ipa:"buːk",ko:"예약하다"},
  "booked": {ipa:"bʊkt",ko:"예약된"},
  "booking": {ipa:"ˈbuːkɪŋ",ko:"예약"},
  "boring": {ipa:"ˈbɔːɹɪŋ",ko:"지루한"},
  "borrow": {ipa:"ˈbɒɹəʊ",ko:"빌리다"},
  "bother": {ipa:"ˈbɒðə",ko:"귀찮게 하다"},
  "bothering": {ipa:"ˈbɒðəɹɪŋ",ko:"방해하는"},
  "bothers": {ipa:"ˈbɒðəz",ko:"거슬리게 하다"},
  "box": {ipa:"bɒks",ko:"상자"},
  "breakfast": {ipa:"ˈbɹɛkfəst",ko:"아침 식사"},
  "bring": {ipa:"ˈbɹɪŋ",ko:"가져오다"},
  "brings": {ipa:"ˈbɹɪŋz",ko:"데려오다"},
  "broken": {ipa:"ˈbɹəʊkən",ko:"고장난"},
  "browsing": {ipa:"ˈbɹaʊzɪŋ",ko:"둘러보는"},
  "buckle": {ipa:"ˈbʌk(ə)l",ko:"채우다"},
  "bug": {ipa:"bʌɡ",ko:"벌레"},
  "burden": {ipa:"ˈbɜːdn",ko:"부담을 주다"},
  "burned": {ipa:"ˈbɜː(ɹ)nd",ko:"소진된"},
  "bus": {ipa:"bʌs",ko:"버스"},
  "busy": {ipa:"ˈbɪzi",ko:"바쁜"},
  "but": {ipa:"bʌt"},
  "buy": {ipa:"baɪ",ko:"사다"},
  "by": {ipa:"baɪ"},
  "cab": {ipa:"kæb",ko:"택시"},
  "cafe": {ipa:"ˈkæfeɪ",ko:"카페"},
  "call": {ipa:"kɔːɫ",ko:"부르다, 전화하다"},
  "camera": {ipa:"ˈkæməɹə",ko:"카메라"},
  "can": {ipa:"ˈkæn"},
  "can't": {ipa:"kɑːnt"},
  "cancel": {ipa:"ˈkænsl̩",ko:"취소하다"},
  "canceled": {ipa:"ˈkænsəld",ko:"취소된"},
  "cancelled": {ipa:"ˈkænsəld",ko:"취소된"},
  "cannot": {ipa:"kəˈnɑt",ko:"할 수 없다"},
  "card": {ipa:"kɑːd",ko:"카드"},
  "cards": {ipa:"kɑːdz",ko:"카드"},
  "care": {ipa:"kɛə",ko:"돌봄, 신경 씀"},
  "carry": {ipa:"ˈkæ.ɹi",ko:"나르다"},
  "carry-on": {ipa:"ˈkæri ɒn",ko:"기내 반입용"},
  "carrying": {ipa:"ˈkæ.ɹiɪŋ",ko:"소지한"},
  "carryon": {ipa:"ˈkæri ɒn",ko:"기내 반입용"},
  "cart": {ipa:"kɑːt",ko:"수레"},
  "cash": {ipa:"kæʃ",ko:"현금"},
  "catch": {ipa:"kæt͡ʃ",ko:"잡다, 걸리다"},
  "cats": {ipa:"kæts",ko:"고양이"},
  "certain": {ipa:"ˈsɜːtən",ko:"확실한"},
  "change": {ipa:"tʃeɪndʒ",ko:"바꾸다, 잔돈"},
  "changed": {ipa:"t͡ʃeɪnd͡ʒd",ko:"바뀐"},
  "changing": {ipa:"ˈtʃeɪndʒɪŋ",ko:"바꾸는"},
  "charge": {ipa:"t͡ʃɑːd͡ʒ",ko:"요금"},
  "charger": {ipa:"ˈtʃɑːdʒə",ko:"충전기"},
  "cheaper": {ipa:"ˈtʃiːpə",ko:"더 싼"},
  "check": {ipa:"t͡ʃɛk",ko:"확인하다, 계산서"},
  "check-in": {ipa:"ˈtʃek ɪn",ko:"체크인"},
  "check-out": {ipa:"ˈtʃek aʊt",ko:"체크아웃"},
  "checked": {ipa:"tʃɛkt",ko:"부친, 확인한"},
  "checkout": {ipa:"ˈtʃekaʊt",ko:"체크아웃"},
  "checkpoint": {ipa:"ˈtʃekpɔɪnt",ko:"검색대"},
  "chicken": {ipa:"ˈt͡ʃɪkɪn",ko:"닭고기"},
  "child": {ipa:"t͡ʃaɪld",ko:"아이"},
  "children": {ipa:"ˈtʃɪldɹən",ko:"아이들"},
  "chilly": {ipa:"ˈtʃɪli",ko:"쌀쌀한"},
  "chin": {ipa:"tʃɪn",ko:"턱"},
  "cilantro": {ipa:"siˈlæntɹəʊ",ko:"고수"},
  "city": {ipa:"ˈsɪti",ko:"도시"},
  "claim": {ipa:"kleɪm",ko:"찾다, 청구하다"},
  "clean": {ipa:"kliːn",ko:"청소하다"},
  "cleaned": {ipa:"kliːnd",ko:"청소된"},
  "cleared": {ipa:"klɪəd",ko:"통과된"},
  "clogged": {ipa:"klɒɡd",ko:"막힌"},
  "close": {ipa:"kləʊz",ko:"닫다, 가까운"},
  "coffee": {ipa:"ˈkɑ.fi",ko:"커피"},
  "cold": {ipa:"kəʊld",ko:"추운, 감기"},
  "colleague": {ipa:"ˈkɒliːɡ",ko:"동료"},
  "color": {ipa:"ˈkʌl.ə(ɹ)",ko:"색"},
  "colour": {ipa:"ˈkʌlə",ko:"색"},
  "come": {ipa:"kʌm",ko:"오다"},
  "comfortable": {ipa:"ˈkʌm.fə.tə.bəl",ko:"편안한"},
  "coming": {ipa:"ˈkʌmɪŋ",ko:"다가오는"},
  "commute": {ipa:"kəˈmjuːt",ko:"통근"},
  "completely": {ipa:"kəmˈpliːtli",ko:"완전히"},
  "conditioner": {ipa:"kənˈdɪʃənə",ko:"조절기"},
  "confirm": {ipa:"kənˈfɜːm",ko:"확인하다"},
  "confused": {ipa:"kənˈfjuːzd",ko:"헷갈리는"},
  "confusing": {ipa:"kənˈfjuːzɪŋ",ko:"헷갈리게 하는"},
  "congratulations": {ipa:"kənˌɡɹad͡ʒəˈleɪʃ(ə)nz",ko:"축하합니다"},
  "connecting": {ipa:"kəˈnɛktɪŋ",ko:"연결되는"},
  "connection": {ipa:"kəˈnɛkʃən",ko:"연결, 환승"},
  "contain": {ipa:"kənˈteɪn",ko:"포함하다"},
  "convenience": {ipa:"kənˈviːnɪəns",ko:"편의"},
  "convinced": {ipa:"kənˈvɪnst",ko:"확신하는"},
  "corner": {ipa:"ˈkɔːnə(ɹ)",ko:"모퉁이"},
  "could": {ipa:"kʊd"},
  "couldn't": {ipa:"ˈkʊdənt"},
  "count": {ipa:"kaʊnt",ko:"믿다, 세다"},
  "counter": {ipa:"ˈkaʊntə",ko:"카운터"},
  "coupon": {ipa:"ˈkuːˌpɒn",ko:"쿠폰"},
  "cozy": {ipa:"ˈkoʊzi",ko:"아늑한"},
  "cross": {ipa:"kɹɑs",ko:"건너다"},
  "cup": {ipa:"kʌp",ko:"컵"},
  "curfew": {ipa:"ˈkɜː.fjuː",ko:"통금"},
  "customs": {ipa:"ˈkʌstəmz",ko:"세관"},
  "cute": {ipa:"kjuːt",ko:"귀여운"},
  "cutting": {ipa:"ˈkʌtɪŋ",ko:"끊기는"},
  "damaged": {ipa:"ˈdæmɪdʒd",ko:"파손된"},
  "day": {ipa:"deɪ",ko:"날"},
  "declaration": {ipa:"ˌdɛkləˈɹeɪʃən",ko:"신고"},
  "declare": {ipa:"dɪˈkleə",ko:"신고하다"},
  "degree": {ipa:"dɪˈɡɹiː",ko:"정도"},
  "delay": {ipa:"dɪˈleɪ",ko:"지연"},
  "delayed": {ipa:"dəˈleɪd",ko:"지연된"},
  "delicious": {ipa:"dɪˈlɪʃəs",ko:"맛있는"},
  "departed": {ipa:"dɪˈpɑːtɪd",ko:"떠났다"},
  "departing": {ipa:"dɪˈpɑːtɪŋ",ko:"떠나는"},
  "depend": {ipa:"dɪˈpɛnd",ko:"달려 있다"},
  "depends": {ipa:"dɪˈpɛndz",ko:"달려 있다"},
  "deposit": {ipa:"dɪˈpɒzɪt",ko:"보증금"},
  "desk": {ipa:"dɛsk",ko:"창구"},
  "dessert": {ipa:"dɪˈzɜːt",ko:"디저트"},
  "destination": {ipa:"dɛstɪˈneɪʃən",ko:"목적지"},
  "did": {ipa:"dɪd"},
  "didn't": {ipa:"ˈdɪdənt"},
  "difference": {ipa:"ˈdɪfəɹən(t)s",ko:"차이"},
  "different": {ipa:"ˈdɪf.(ə)ɹ.ənt",ko:"다른"},
  "differently": {ipa:"ˈdifəɹəntli",ko:"다르게"},
  "difficult": {ipa:"ˈdɪfɪkəlt",ko:"어려운"},
  "disagree": {ipa:"dɪsəˈɡɹiː",ko:"동의하지 않다"},
  "disappointed": {ipa:"ˌdɪsəˈpɔɪntɪd",ko:"실망한"},
  "disappointment": {ipa:"dɪsəˈpɔɪntmənt",ko:"실망"},
  "discount": {ipa:"dɪsˈkaʊnt",ko:"할인"},
  "dish": {ipa:"dɪʃ",ko:"요리"},
  "distance": {ipa:"ˈdɪs.təns",ko:"거리"},
  "disturb": {ipa:"dɪsˈtɜːb",ko:"방해하다"},
  "disturbing": {ipa:"dɪsˈtɜːbɪŋ",ko:"방해하는"},
  "do": {ipa:"duː"},
  "doable": {ipa:"ˈduːəbl",ko:"할 만한"},
  "does": {ipa:"dʌz"},
  "doesn't": {ipa:"ˈdʌzənt"},
  "doggy": {ipa:"ˈdɒ.ɡi",ko:"강아지"},
  "doing": {ipa:"ˈduːɪŋ",ko:"하는 중"},
  "don't": {ipa:"dəʊnt"},
  "door": {ipa:"dɔː",ko:"문"},
  "doubtful": {ipa:"ˈdaʊtfəl",ko:"의심스러운"},
  "down": {ipa:"daʊn"},
  "drain": {ipa:"dɹeɪn",ko:"물이 빠지다"},
  "drink": {ipa:"dɹɪŋk",ko:"마시다"},
  "drinker": {ipa:"ˈdrɪŋkə",ko:"술 마시는 사람"},
  "drive": {ipa:"dɹaɪv",ko:"운전하다"},
  "drop": {ipa:"dɹɒp",ko:"내려주다"},
  "dropping": {ipa:"ˈdɹɒpɪŋ",ko:"끊기는"},
  "dull": {ipa:"dəl",ko:"따분한"},
  "duty-free": {ipa:"ˈdjuːti friː",ko:"면세의"},
  "dutyfree": {ipa:"ˈdjuːti friː",ko:"면세의"},
  "dwell": {ipa:"dwɛl",ko:"곱씹다"},
  "earlier": {ipa:"ˈɜː.lɪə",ko:"더 일찍"},
  "early": {ipa:"ˈɜː.li",ko:"이른"},
  "earphones": {ipa:"ˈɪəfoʊnz",ko:"이어폰"},
  "ease": {ipa:"iːz",ko:"편안함"},
  "easy": {ipa:"ˈiːzi",ko:"쉬운"},
  "elevator": {ipa:"ˈelɪveɪtə",ko:"엘리베이터"},
  "email": {ipa:"ˈiːmeɪl",ko:"이메일"},
  "empty": {ipa:"ˈɛmpti",ko:"비우다, 빈"},
  "end": {ipa:"ɛnd",ko:"끝"},
  "enjoyed": {ipa:"ɪnˈdʒɔɪd",ko:"즐겼다"},
  "enough": {ipa:"iˈnʌf",ko:"충분한"},
  "enter": {ipa:"ˈɛntə(ɹ)",ko:"들어가다"},
  "envious": {ipa:"ˈɛnvɪəs",ko:"부러운"},
  "especially": {ipa:"əˈspɛʃ(ə)li",ko:"특히"},
  "even": {ipa:"ˈiːvən"},
  "everything": {ipa:"ˈɛvɹiθɪŋ",ko:"모든 것"},
  "example": {ipa:"əɡˈzæmpl̩",ko:"예"},
  "excellent": {ipa:"ˈɛksələnt",ko:"훌륭한"},
  "excess": {ipa:"əkˈsɛs",ko:"초과"},
  "exchange": {ipa:"ɛksˈtʃeɪndʒ",ko:"교환하다, 환전하다"},
  "excited": {ipa:"ɪkˈsaɪtɪd",ko:"신나는"},
  "excuse": {ipa:"ɪkˈskjuːz",ko:"실례"},
  "excused": {ipa:"ɛksˈkjuːzd",ko:"양해를 구한"},
  "exit": {ipa:"ˈɛksɪt",ko:"출구, 비상구"},
  "expect": {ipa:"ɛkˈspɛkt",ko:"기대하다"},
  "expectations": {ipa:"ɛkspɛkˈteɪʃənz",ko:"기대"},
  "expected": {ipa:"ɪksˈpɛktɪd",ko:"예상한"},
  "expensive": {ipa:"ɛkˈspɛnsɪv",ko:"비싼"},
  "explain": {ipa:"ɛkˈspleɪn",ko:"설명하다"},
  "explains": {ipa:"ɛkˈspleɪnz",ko:"설명하다"},
  "extend": {ipa:"ɛkˈstɛnd",ko:"연장하다"},
  "extent": {ipa:"ɪksˈtɛnt",ko:"정도"},
  "extra": {ipa:"ˈɛkstɹə",ko:"추가의"},
  "eye": {ipa:"aɪ",ko:"눈"},
  "fair": {ipa:"feə",ko:"공평한"},
  "family": {ipa:"ˈfæməli",ko:"가족"},
  "far": {ipa:"fɑː",ko:"먼"},
  "fare": {ipa:"fɛə(ɹ)",ko:"교통 요금"},
  "fast": {ipa:"fɑːst",ko:"빠른"},
  "fasten": {ipa:"ˈfɑːsn̩",ko:"매다"},
  "fault": {ipa:"fɒlt",ko:"잘못"},
  "favor": {ipa:"ˈfeɪvə",ko:"부탁"},
  "favour": {ipa:"ˈfeɪ.və",ko:"부탁"},
  "fed": {ipa:"fɛd",ko:"질린"},
  "fee": {ipa:"fiː",ko:"수수료"},
  "feel": {ipa:"fiːl",ko:"느끼다"},
  "feeling": {ipa:"ˈfiːlɪŋ",ko:"기분"},
  "feelings": {ipa:"ˈfiːlɪŋz",ko:"감정"},
  "feels": {ipa:"fiːlz",ko:"느껴지다"},
  "fell": {ipa:"fɛl",ko:"떨어졌다"},
  "fill": {ipa:"fɪl",ko:"채우다"},
  "final": {ipa:"ˈfaɪ.nəl",ko:"최종의"},
  "find": {ipa:"faɪnd",ko:"찾다"},
  "fine": {ipa:"faɪn",ko:"괜찮은"},
  "finger": {ipa:"ˈfɪŋəɹ",ko:"손가락"},
  "fingers": {ipa:"ˈfɪŋɡəz",ko:"손가락"},
  "first": {ipa:"fɜːst",ko:"첫 번째"},
  "fitting": {ipa:"ˈfɪtɪŋ",ko:"옷을 입어보는"},
  "flies": {ipa:"flaɪz",ko:"날아가다"},
  "flight": {ipa:"flaɪt",ko:"항공편"},
  "floor": {ipa:"flɔː",ko:"층"},
  "flying": {ipa:"ˈflaɪ.ɪŋ",ko:"비행하는"},
  "food": {ipa:"fuːd",ko:"음식"},
  "foot": {ipa:"fʊt",ko:"발"},
  "for": {ipa:"fɔː"},
  "forever": {ipa:"fəˈɹɛvə(ɹ)",ko:"영원히"},
  "forget": {ipa:"fəˈɡɛt",ko:"잊다"},
  "forgot": {ipa:"fəˈɡɒt",ko:"잊었다"},
  "form": {ipa:"fɔːm",ko:"서류"},
  "forward": {ipa:"ˈfɔːwəd",ko:"앞으로"},
  "found": {ipa:"faʊnd",ko:"찾았다"},
  "fragile": {ipa:"ˈfɹædʒaɪl",ko:"깨지기 쉬운"},
  "frank": {ipa:"fɹæŋk",ko:"솔직한"},
  "frankly": {ipa:"ˈfɹæŋkli",ko:"솔직히"},
  "free": {ipa:"fɹiː",ko:"비어 있는, 무료의"},
  "friend": {ipa:"fɹɛnd",ko:"친구"},
  "from": {ipa:"fɹɒm"},
  "frustrating": {ipa:"ˈfɹʌstɹeɪtɪŋ",ko:"답답한"},
  "fun": {ipa:"fʊn",ko:"재미"},
  "gate": {ipa:"ɡeɪt",ko:"탑승구"},
  "get": {ipa:"ɡɛt",ko:"얻다, 되다"},
  "gift": {ipa:"ɡɪft",ko:"선물"},
  "gift-wrap": {ipa:"ˈɡɪft ræp",ko:"선물 포장하다"},
  "give": {ipa:"ɡɪv",ko:"주다"},
  "glad": {ipa:"ɡlæd",ko:"기쁜"},
  "glass": {ipa:"ɡlɑːs",ko:"유리잔"},
  "go": {ipa:"ɡəʊ",ko:"가다"},
  "goes": {ipa:"ɡəʊz",ko:"가다"},
  "going": {ipa:"ˈɡəʊɪŋ",ko:"가는 중"},
  "good": {ipa:"ɡʊd",ko:"좋은"},
  "got": {ipa:"ɡɒt",ko:"얻었다"},
  "grab": {ipa:"ɡɹæb",ko:"간단히 먹다, 잡다"},
  "gratuity": {ipa:"ɡɹəˈtjuːətɪ",ko:"봉사료"},
  "great": {ipa:"ɡɹeɪt",ko:"훌륭한"},
  "gym": {ipa:"dʒɪm",ko:"헬스장"},
  "had": {ipa:"hæd"},
  "hail": {ipa:"heɪl",ko:"택시를 잡다"},
  "hall": {ipa:"hɔːl",ko:"회관"},
  "hand": {ipa:"hænd",ko:"손, 도움"},
  "handle": {ipa:"ˈhæn.dl",ko:"감당하다"},
  "hanging": {ipa:"ˈhæŋɪŋ",ko:"버티는"},
  "happened": {ipa:"ˈhæpənd",ko:"일어났다"},
  "happy": {ipa:"ˈhæpi",ko:"행복한"},
  "hard": {ipa:"hɑːd",ko:"어려운"},
  "harder": {ipa:"ˈhɑːdə",ko:"더 어려운"},
  "has": {ipa:"hæz"},
  "hasn't": {ipa:"ˈhæzənt"},
  "hate": {ipa:"heɪt",ko:"싫어하다"},
  "have": {ipa:"hæv"},
  "haven't": {ipa:"ˈhævənt"},
  "having": {ipa:"ˈhævɪŋ"},
  "he's": {ipa:"hiːz"},
  "heading": {ipa:"ˈhedɪŋ",ko:"향하는"},
  "headphones": {ipa:"ˈhedfoʊnz",ko:"헤드폰"},
  "hear": {ipa:"hɪə(ɹ)",ko:"듣다"},
  "heard": {ipa:"hɜːd",ko:"들었다"},
  "heat": {ipa:"hit",ko:"데우다"},
  "heater": {ipa:"ˈhiːtə",ko:"난방기"},
  "heating": {ipa:"ˈhiːtɪŋ",ko:"난방"},
  "hello": {ipa:"həˈləʊ",ko:"안녕하세요"},
  "help": {ipa:"hɛlp",ko:"돕다, 도움"},
  "here": {ipa:"hɪə"},
  "here's": {ipa:"hɪəz"},
  "hesitate": {ipa:"ˈhɛzɪteɪt",ko:"망설이다"},
  "hi": {ipa:"haɪ",ko:"안녕"},
  "hiking": {ipa:"ˈhaɪkɪŋ",ko:"등산"},
  "hold": {ipa:"həʊld",ko:"붙잡다, 보관하다"},
  "holiday": {ipa:"ˈhɒlɪdeɪ",ko:"휴가, 연휴"},
  "home": {ipa:"həʊm",ko:"집"},
  "honest": {ipa:"ˈɒnɪst",ko:"솔직한"},
  "honestly": {ipa:"ˈɒnɪstli",ko:"솔직히"},
  "hope": {ipa:"həʊp",ko:"바라다"},
  "hoped": {ipa:"həʊpt",ko:"바랐다"},
  "hopeful": {ipa:"ˈhəʊpfəl",ko:"희망적인"},
  "hot": {ipa:"hɒt",ko:"뜨거운, 매운"},
  "hotel": {ipa:"həʊˈtel",ko:"호텔"},
  "housekeeping": {ipa:"ˈhaʊskiːpɪŋ",ko:"객실 정리"},
  "how": {ipa:"haʊ"},
  "how's": {ipa:"haʊz"},
  "hurry": {ipa:"ˈhʌ.ɹi",ko:"서두름"},
  "hurt": {ipa:"hɜːt",ko:"상하게 하다"},
  "i": {ipa:"aɪ"},
  "i'd": {ipa:"aɪd"},
  "i'll": {ipa:"aɪl"},
  "i'm": {ipa:"aɪm"},
  "i've": {ipa:"aɪv"},
  "id": {ipa:"ɪd",ko:"신분증"},
  "idea": {ipa:"aɪˈdɪə",ko:"생각"},
  "if": {ipa:"ɪf"},
  "imagine": {ipa:"ɪˈmædʒ.ɪn",ko:"상상하다"},
  "immigration": {ipa:"ɪmɪˈɡɹeɪʃn",ko:"입국심사"},
  "impressed": {ipa:"ɪmˈpɹɛst",ko:"감탄한"},
  "impressive": {ipa:"ɪmˈpɹɛsɪv",ko:"인상적인"},
  "in": {ipa:"ɪn"},
  "include": {ipa:"ɪnˈkluːd",ko:"포함하다"},
  "included": {ipa:"ɪnˈkluːdɪd",ko:"포함된"},
  "insect": {ipa:"ˈɪnsɛkt",ko:"곤충"},
  "instead": {ipa:"ɪnˈstɛd",ko:"대신에"},
  "interested": {ipa:"ˈɪntəɹɛstəd",ko:"관심 있는"},
  "interesting": {ipa:"ˈɪnt(ə)ɹɛstɪŋ",ko:"흥미로운"},
  "interrupting": {ipa:"ˌɪntəˈrʌptɪŋ",ko:"방해하는"},
  "interview": {ipa:"ˈɪntəvjuː",ko:"면접"},
  "into": {ipa:"ˈɪn.tuː"},
  "introduce": {ipa:"ˌɪntɹəˈdjuːs",ko:"소개하다"},
  "iron": {ipa:"ˈaɪən",ko:"다리미"},
  "is": {ipa:"ɪz"},
  "isn't": {ipa:"ˈɪzənt"},
  "it": {ipa:"ɪt"},
  "it'll": {ipa:"ˈɪtəl"},
  "it's": {ipa:"ɪts"},
  "jealous": {ipa:"ˈdʒɛləs",ko:"부러운"},
  "job": {ipa:"d͡ʒɒb",ko:"직장"},
  "joking": {ipa:"ˈdʒəʊkɪŋ",ko:"농담하는"},
  "journey": {ipa:"ˈd͡ʒɜːni",ko:"여정"},
  "jun": {ipa:"dʒʌn"},
  "just": {ipa:"d͡ʒʌst"},
  "keen": {ipa:"kiːn",ko:"관심 있는"},
  "keep": {ipa:"kiːp",ko:"유지하다, 맡다"},
  "keeps": {ipa:"kiːps",ko:"계속 ~하다"},
  "key": {ipa:"kiː",ko:"열쇠"},
  "kidding": {ipa:"ˈkɪdɪŋ",ko:"농담하는"},
  "kids": {ipa:"kɪ(d)z",ko:"아이들"},
  "kim": {ipa:"kɪm"},
  "kind": {ipa:"kaɪnd",ko:"종류, 친절한"},
  "knew": {ipa:"ˈnjuː",ko:"알았다"},
  "know": {ipa:"nəʊ",ko:"알다"},
  "korean": {ipa:"kəˈriːən",ko:"한국어"},
  "landing": {ipa:"ˈlændɪŋ",ko:"착륙"},
  "laptop": {ipa:"ˈlæp.tɒp",ko:"노트북"},
  "larger": {ipa:"ˈlɑː.d͡ʒə",ko:"더 큰"},
  "last": {ipa:"last",ko:"지난, 마지막"},
  "late": {ipa:"leɪt",ko:"늦은"},
  "lately": {ipa:"ˈleɪt.li",ko:"요즘"},
  "later": {ipa:"ˈleɪtə",ko:"나중에"},
  "laundry": {ipa:"ˈlɑn.dɹi",ko:"세탁"},
  "lavatory": {ipa:"ˈlæv.ə.təɹ.i",ko:"기내 화장실"},
  "layover": {ipa:"ˈleɪoʊvə",ko:"환승 대기"},
  "learned": {ipa:"ˈlɜːnd",ko:"배웠다"},
  "learnt": {ipa:"ˈlɜːnt",ko:"배웠다"},
  "leave": {ipa:"liːv",ko:"남기다, 떠나다"},
  "left": {ipa:"lɛft",ko:"왼쪽, 두고 왔다"},
  "less": {ipa:"lɛs",ko:"덜"},
  "let": {ipa:"lɛt",ko:"~하게 하다"},
  "let's": {ipa:"lɛts"},
  "letdown": {ipa:"ˈletdaʊn",ko:"실망"},
  "level": {ipa:"ˈlɛv.əl",ko:"층, 수준"},
  "lifesaver": {ipa:"ˈlaɪfseɪvə",ko:"은인"},
  "lift": {ipa:"lɪft",ko:"엘리베이터, 태워주기"},
  "light": {ipa:"laɪt",ko:"불, 등"},
  "like": {ipa:"laɪk",ko:"같은, 좋아하다"},
  "limit": {ipa:"ˈlɪmɪt",ko:"한도"},
  "line": {ipa:"laɪn",ko:"줄"},
  "listen": {ipa:"ˈlɪs.ən",ko:"듣다"},
  "little": {ipa:"ˈlɪtəl",ko:"조금, 작은"},
  "live": {ipa:"lɪv",ko:"살다"},
  "lived": {ipa:"lɪvd",ko:"살았다"},
  "living": {ipa:"ˈlɪvɪŋ",ko:"생계, 사는"},
  "load": {ipa:"ləʊd",ko:"짐, 부담"},
  "lock": {ipa:"lɒk",ko:"잠그다"},
  "locked": {ipa:"lɒkt",ko:"잠갔다"},
  "long": {ipa:"ˈlɔːŋ",ko:"긴, 오래"},
  "longer": {ipa:"ˈlɑŋ.ɡɚ",ko:"더 오래"},
  "look": {ipa:"lʊk",ko:"보다"},
  "looking": {ipa:"ˈlʊkɪŋ",ko:"보는 중"},
  "looks": {ipa:"lʊks",ko:"~해 보이다"},
  "loss": {ipa:"lɑs",ko:"잃음"},
  "lost": {ipa:"lɒst",ko:"잃어버린, 길을 잃은"},
  "lot": {ipa:"lɒt",ko:"많음"},
  "louder": {ipa:"ˈlaʊdə",ko:"더 크게"},
  "love": {ipa:"lʊv",ko:"좋아하다"},
  "lovely": {ipa:"ˈlʌvli",ko:"좋은, 사랑스러운"},
  "low": {ipa:"ləʊ",ko:"낮은"},
  "lower": {ipa:"ˈləʊə",ko:"내리다"},
  "luggage": {ipa:"ˈlʌɡɪd͡ʒ",ko:"짐"},
  "made": {ipa:"meɪd",ko:"만들었다, 정돈했다"},
  "make": {ipa:"meɪk",ko:"만들다"},
  "makes": {ipa:"meɪks",ko:"만들다"},
  "manageable": {ipa:"ˈmænɪd͡ʒəbl̩",ko:"감당할 만한"},
  "many": {ipa:"ˈmæni"},
  "map": {ipa:"mæp",ko:"지도"},
  "marked": {ipa:"ˈmɑːkɪd",ko:"표시된"},
  "married": {ipa:"ˈmæɹ.ɪd",ko:"결혼한"},
  "matter": {ipa:"ˈmætə",ko:"중요하다"},
  "may": {ipa:"meɪ"},
  "me": {ipa:"miː"},
  "meal": {ipa:"miːl",ko:"식사"},
  "mean": {ipa:"miːn",ko:"뜻하다"},
  "medium": {ipa:"ˈmiːdɪəm",ko:"중간의"},
  "meet": {ipa:"miːt",ko:"만나다"},
  "meeting": {ipa:"ˈmiːtɪŋ",ko:"만남"},
  "mention": {ipa:"ˈmɛnʃən",ko:"언급하다"},
  "menu": {ipa:"ˈmɛnju",ko:"메뉴판"},
  "message": {ipa:"ˈmɛsɪd͡ʒ",ko:"메시지"},
  "metro": {ipa:"ˈmɛtɹəʊ",ko:"지하철"},
  "might": {ipa:"maɪt"},
  "milk": {ipa:"mɪlk",ko:"우유"},
  "mind": {ipa:"maɪnd",ko:"꺼리다, 마음"},
  "mine": {ipa:"maɪn"},
  "minibar": {ipa:"ˈmɪnibɑː",ko:"미니바"},
  "minsu": {ipa:"ˈminsuː"},
  "minute": {ipa:"ˈmɪnɪt",ko:"분, 잠깐"},
  "minutes": {ipa:"ˈmɪnɪts",ko:"분"},
  "mirror": {ipa:"ˈmɪɹə",ko:"거울"},
  "miss": {ipa:"mɪs",ko:"놓치다"},
  "missed": {ipa:"mɪst",ko:"놓쳤다"},
  "mistake": {ipa:"mɪˈsteɪk",ko:"실수"},
  "mixed": {ipa:"mɪkst",ko:"뒤섞인"},
  "moment": {ipa:"ˈməʊmənt",ko:"잠깐"},
  "money": {ipa:"ˈmʌni",ko:"돈"},
  "more": {ipa:"ˈmɔː"},
  "move": {ipa:"muːv",ko:"옮기다"},
  "moved": {ipa:"muːvd",ko:"감동한, 옮겼다"},
  "much": {ipa:"mʌt͡ʃ"},
  "music": {ipa:"ˈmjuːzɪk",ko:"음악"},
  "my": {ipa:"maɪ"},
  "myself": {ipa:"maɪˈsɛlf",ko:"나 자신"},
  "name": {ipa:"neɪm",ko:"이름"},
  "nauseous": {ipa:"ˈnɑːʃəs",ko:"메스꺼운"},
  "nearby": {ipa:"ˌnɪəˈbaɪ",ko:"근처의"},
  "nearest": {ipa:"ˈnɪəɹɪst",ko:"가장 가까운"},
  "necessary": {ipa:"ˈnɛsəsɹɪ",ko:"필요한"},
  "need": {ipa:"niːd",ko:"필요하다"},
  "nervous": {ipa:"ˈnɜːvəs",ko:"긴장한"},
  "new": {ipa:"njuː",ko:"새로운"},
  "news": {ipa:"njuːz",ko:"소식"},
  "next": {ipa:"nɛkst",ko:"다음의"},
  "nice": {ipa:"naɪs",ko:"좋은"},
  "night": {ipa:"naɪt",ko:"밤, 1박"},
  "no": {ipa:"nəʊ"},
  "noisy": {ipa:"ˈnɔɪzi",ko:"시끄러운"},
  "non-smoking": {ipa:"nɒn ˈsmoʊkɪŋ",ko:"금연의"},
  "nonsmoking": {ipa:"nɒn ˈsmoʊkɪŋ",ko:"금연의"},
  "not": {ipa:"nɒt"},
  "nothing": {ipa:"ˈnʌθɪŋ",ko:"아무것도 없음"},
  "now": {ipa:"naʊ",ipa:"naʊ",ko:"지금"},
  "now's": {ipa:"naʊz"},
  "nuisance": {ipa:"ˈnjuːsəns",ko:"성가신 사람"},
  "number": {ipa:"ˈnʌmbə",ko:"번호"},
  "of": {ipa:"əv"},
  "off": {ipa:"ɔːf"},
  "offended": {ipa:"əˈfɛndɪd",ko:"기분 상한"},
  "offer": {ipa:"ˈɑfɚ",ko:"제공하다"},
  "office": {ipa:"ˈɑfɪs",ko:"사무실"},
  "often": {ipa:"ˈɑf(t)ən",ko:"자주"},
  "ok": {ipa:"ˌoʊˈkeɪ",ko:"괜찮은"},
  "okay": {ipa:"ˌəʊˈkeɪ",ko:"괜찮은"},
  "on": {ipa:"ɒn"},
  "one": {ipa:"wʌn"},
  "online": {ipa:"ɒnˈlaɪn",ko:"온라인으로"},
  "only": {ipa:"ˈəʊn.li"},
  "open": {ipa:"ˈəʊ.pən",ko:"열다"},
  "opening": {ipa:"ˈəʊ.pənɪŋ",ko:"빈자리"},
  "opinion": {ipa:"əˈpɪnjən",ko:"의견"},
  "optimistic": {ipa:"ˌɒptɪˈmɪstɪk",ko:"낙관적인"},
  "or": {ipa:"ɔː(ɹ)"},
  "order": {ipa:"ˈɔːdə",ko:"주문하다"},
  "ordered": {ipa:"ˈɔːdəd",ko:"주문했다"},
  "our": {ipa:"ˈaʊə"},
  "out": {ipa:"aʊt"},
  "outdoors": {ipa:"ˌaʊtˈdɔːz",ko:"야외에"},
  "outside": {ipa:"ˌaʊtˈsaɪd",ko:"밖에"},
  "over": {ipa:"ˈəʊ.və(ɹ)"},
  "overhead": {ipa:"ˈəʊvəˌhɛd",ko:"머리 위의"},
  "overkill": {ipa:"ˈoʊvəkɪl",ko:"과한 것"},
  "overweight": {ipa:"ˌoʊvəˈweɪt",ko:"무게 초과의"},
  "owe": {ipa:"əʊ",ko:"빚지다"},
  "pair": {ipa:"pɛə(ɹ)",ko:"한 쌍"},
  "parents": {ipa:"ˈpɛəɹənts",ko:"부모님"},
  "particularly": {ipa:"pəˈtɪkjəli",ko:"특별히"},
  "pass": {ipa:"pɑːs",ko:"통행증, 건네다"},
  "passport": {ipa:"ˈpɑːspɔːt",ko:"여권"},
  "password": {ipa:"ˈpæswɜːd",ko:"비밀번호"},
  "pay": {ipa:"peɪ",ko:"지불하다"},
  "peanuts": {ipa:"ˈpiːˌnʌts",ko:"땅콩"},
  "peek": {ipa:"piːk",ko:"살짝 보기"},
  "pen": {ipa:"pɛn",ko:"펜"},
  "per": {ipa:"pɜː(ɹ)",ko:"~당"},
  "permission": {ipa:"pəˈmɪʃən",ko:"허락"},
  "personal": {ipa:"ˈpɜː.sən.əl",ko:"개인의"},
  "pest": {ipa:"pɛst",ko:"성가신 사람"},
  "pet": {ipa:"pɛt",ko:"반려동물"},
  "picture": {ipa:"ˈpɪktʃə",ko:"사진"},
  "pillow": {ipa:"ˈpɪləʊ",ko:"베개"},
  "pitch": {ipa:"pɪtʃ",ko:"거들다"},
  "pity": {ipa:"ˈpɪti",ko:"안타까움"},
  "place": {ipa:"pleɪs",ko:"장소, 대신"},
  "plans": {ipa:"plænz",ko:"계획"},
  "pleasant": {ipa:"ˈplɛzənt",ko:"쾌적한"},
  "please": {ipa:"pliːz",ko:"부디"},
  "pleasure": {ipa:"ˈplɛʒə",ko:"기쁨"},
  "pockets": {ipa:"ˈpɒkɪts",ko:"주머니"},
  "point": {ipa:"pɔɪnt",ko:"요점"},
  "pool": {ipa:"pul",ko:"수영장"},
  "portion": {ipa:"ˈpɔːʃən",ko:"1인분"},
  "position": {ipa:"pəˈzɪʃ(ə)n",ko:"위치, 자세"},
  "possible": {ipa:"ˈpɒsɪbl̩",ko:"가능한"},
  "postpone": {ipa:"poʊstˈpoʊn",ko:"미루다"},
  "pressure": {ipa:"ˈpɹeʃə",ko:"압박, 수압"},
  "pretty": {ipa:"ˈpɹɪti",ko:"꽤"},
  "price": {ipa:"pɹaɪs",ko:"가격"},
  "privacy": {ipa:"ˈpɹaɪv.ə.sɪ",ko:"사생활"},
  "promotion": {ipa:"pɹəˈməʊʃən",ko:"승진"},
  "purpose": {ipa:"ˈpɜːpəs",ko:"목적"},
  "put": {ipa:"pʊt",ko:"놓다"},
  "queue": {ipa:"kjuː",ko:"줄"},
  "quiet": {ipa:"ˈkwaɪ.ət",ko:"조용한"},
  "quieter": {ipa:"ˈkwaɪ.ə.tɚ",ko:"더 조용한"},
  "rain": {ipa:"ɹeɪn",ko:"비"},
  "raise": {ipa:"ɹeɪz",ko:"들어올리다"},
  "rare": {ipa:"ɹeə",ko:"덜 익힌"},
  "rather": {ipa:"ˈɹɑːðə",ko:"차라리"},
  "reach": {ipa:"ɹiːt͡ʃ",ko:"도달하다"},
  "ready": {ipa:"ˈɹɛdi",ko:"준비된"},
  "really": {ipa:"ˈɹɪəli",ko:"정말"},
  "reasonable": {ipa:"ˈɹiː.zən.ə.bəl",ko:"타당한"},
  "reassuring": {ipa:"ˌriːəˈʃʊərɪŋ",ko:"안심시키는"},
  "receipt": {ipa:"ɹɪˈsiːt",ko:"영수증"},
  "receive": {ipa:"ɹɪˈsiːv",ko:"받다"},
  "recline": {ipa:"ɹəˈklaɪn",ko:"뒤로 젖히다"},
  "recommend": {ipa:"ɹɛkəˈmɛnd",ko:"추천하다"},
  "reduce": {ipa:"ɹɪˈdjuːs",ko:"줄이다"},
  "refill": {ipa:"ˈɹiː.fɪl",ko:"리필"},
  "refund": {ipa:"ˈriːfʌnd",ko:"환불"},
  "regards": {ipa:"ɹɪˈɡɑːdz",ko:"안부"},
  "regrets": {ipa:"rɪˈɡrets",ko:"후회"},
  "relaxing": {ipa:"rɪˈlæksɪŋ",ko:"편안한"},
  "relief": {ipa:"ɹɪˈliːf",ko:"안도"},
  "rely": {ipa:"ɹɪˈlaɪ",ko:"의지하다"},
  "remarkable": {ipa:"ɹɪˈmɑːkəbl̩",ko:"놀라운"},
  "remember": {ipa:"ɹɪˈmɛmbə",ko:"기억하다"},
  "remove": {ipa:"ɹɪˈmuːv",ko:"벗다, 없애다"},
  "report": {ipa:"ɹɪˈpɔːt",ko:"신고하다"},
  "requested": {ipa:"ɹɪˈkwɛstɪd",ko:"요청했다"},
  "required": {ipa:"ɹɪˈkwaɪəd",ko:"필요한"},
  "reservation": {ipa:"ˌɹɛzəˈveɪʃən",ko:"예약"},
  "reserved": {ipa:"ɹɪˈzɜːvd",ko:"예약된"},
  "resonates": {ipa:"ˈrezəneɪts",ko:"공감되다"},
  "rest": {ipa:"ɹɛst",ko:"휴식"},
  "restaurant": {ipa:"ˈɹɛs.t(ə).ɹ(ə)nt",ko:"식당"},
  "restroom": {ipa:"ˈrestruːm",ko:"화장실"},
  "result": {ipa:"ɹɪˈzʌlt",ko:"결과"},
  "return": {ipa:"ɹɪˈtɜːn",ko:"돌아오는, 반품하다"},
  "ride": {ipa:"ɹaɪd",ko:"태워주기"},
  "ridiculous": {ipa:"ɹɪˈdɪkjʊləs",ko:"터무니없는"},
  "right": {ipa:"ˈɹaɪt",ko:"오른쪽, 맞는"},
  "room": {ipa:"ɹuːm",ko:"방"},
  "rooms": {ipa:"ɹuːmz",ko:"방"},
  "roundtrip": {ipa:"ˈraʊndtrɪp",ko:"왕복의"},
  "row": {ipa:"ˈɹəʊ",ko:"열"},
  "run": {ipa:"ɹʊn",ko:"다니다, 달리다"},
  "running": {ipa:"ˈɹʌnɪŋ",ko:"~하는 중"},
  "rush": {ipa:"ɹʌʃ",ko:"서두름"},
  "safe": {ipa:"seɪf",ko:"안전한, 금고"},
  "safely": {ipa:"ˈseɪfli",ko:"안전하게"},
  "sale": {ipa:"seɪl",ko:"할인 판매"},
  "same": {ipa:"seɪm",ko:"같은"},
  "sauce": {ipa:"sɔːs",ko:"소스"},
  "save": {ipa:"seɪv",ko:"맡아두다"},
  "say": {ipa:"seɪ",ko:"말하다"},
  "scan": {ipa:"skæn",ko:"읽히다"},
  "scared": {ipa:"skɛəd",ko:"겁먹은"},
  "schedule": {ipa:"ˈskɛ.dʒu.əl",ko:"일정"},
  "school": {ipa:"skuːl",ko:"학교"},
  "scoot": {ipa:"skuːt",ko:"옆으로 비키다"},
  "seat": {ipa:"siːt",ko:"자리"},
  "seats": {ipa:"siːts",ko:"자리"},
  "second": {ipa:"ˈsekənd",ko:"두 번째, 잠깐"},
  "security": {ipa:"sɪˈkjʊəɹəti",ko:"보안"},
  "see": {ipa:"siː",ko:"보다, 만나다"},
  "seeing": {ipa:"ˈsiːɪŋ",ko:"보는 것"},
  "seems": {ipa:"siːmz",ko:"~해 보이다"},
  "send": {ipa:"sɛnd",ko:"보내다"},
  "sense": {ipa:"sɛn(t)s",ko:"뜻, 이치"},
  "sent": {ipa:"sɛnt",ko:"보냈다"},
  "separately": {ipa:"ˈseprətli",ko:"따로"},
  "serious": {ipa:"ˈsɪə.ɹi.əs",ko:"진지한"},
  "served": {ipa:"sɜːvd",ko:"제공되는"},
  "service": {ipa:"ˈsɜːvɪs",ko:"서비스"},
  "serving": {ipa:"ˈsɜːvɪŋ",ko:"1인분"},
  "seven": {ipa:"ˈsɛv.ən"},
  "shade": {ipa:"ʃeɪd",ko:"덮개"},
  "shame": {ipa:"ʃeɪm",ko:"아쉬움"},
  "share": {ipa:"ʃɛə",ko:"나누다"},
  "she's": {ipa:"ʃiːz"},
  "sheets": {ipa:"ʃiːts",ko:"침대 시트"},
  "shift": {ipa:"ʃɪft",ko:"옮기다"},
  "shoes": {ipa:"ʃuːz",ko:"신발"},
  "shop": {ipa:"ʃɒp",ko:"가게"},
  "short": {ipa:"ʃɔːt",ko:"짧은, 모자란"},
  "shortly": {ipa:"ˈʃɔːtli",ko:"곧"},
  "shot": {ipa:"ʃɒt",ko:"시도"},
  "should": {ipa:"ʃʊd"},
  "show": {ipa:"ʃəʊ",ko:"보여주다"},
  "shut": {ipa:"ʃʌt",ko:"닫다"},
  "shuttle": {ipa:"ˈʃʌtl",ko:"셔틀"},
  "siblings": {ipa:"ˈsɪblɪŋz",ko:"형제자매"},
  "sick": {ipa:"sɪk",ko:"아픈"},
  "side": {ipa:"saɪd",ko:"옆, 곁들이"},
  "sim": {ipa:"sɪm",ko:"유심"},
  "since": {ipa:"sɪns",ko:"~한 이후로"},
  "sink": {ipa:"sɪŋk",ko:"세면대"},
  "sit": {ipa:"sɪt",ko:"앉다"},
  "sits": {ipa:"sɪts",ko:"앉다, 받아들여지다"},
  "situation": {ipa:"sɪtjuːˈeɪʃən",ko:"상황"},
  "size": {ipa:"saɪz",ko:"크기"},
  "skeptical": {ipa:"ˈskeptɪkəl",ko:"회의적인"},
  "slipped": {ipa:"slɪpt",ko:"미끄러졌다, 깜빡했다"},
  "slowly": {ipa:"ˈsləʊli",ko:"천천히"},
  "small": {ipa:"smɔːl",ko:"작은"},
  "smallest": {ipa:"ˈsmɔːlɪst",ko:"가장 작은"},
  "smell": {ipa:"smɛl",ko:"냄새 맡다"},
  "smells": {ipa:"smɛlz",ko:"냄새가 나다"},
  "smoke": {ipa:"sməʊk",ko:"담배 연기"},
  "so": {ipa:"səʊ"},
  "sold": {ipa:"ˈsəʊld",ko:"납득된, 팔린"},
  "solid": {ipa:"ˈsɒlɪd",ko:"부탁, 단단한"},
  "some": {ipa:"sʌm"},
  "something": {ipa:"ˈsʌmθɪŋ",ko:"무언가"},
  "sometime": {ipa:"ˈsʌmˌtaɪm",ko:"언젠가"},
  "soon": {ipa:"suːn",ko:"곧"},
  "sorry": {ipa:"ˈsɔɹi",ko:"미안한, 유감스러운"},
  "sounds": {ipa:"saʊndz",ko:"~처럼 들리다"},
  "soy": {ipa:"sɔɪ",ko:"콩"},
  "space": {ipa:"speɪs",ko:"공간"},
  "spare": {ipa:"ˈspɛə(ɹ)",ko:"여분의"},
  "speak": {ipa:"spiːk",ko:"말하다"},
  "special": {ipa:"ˈspɛ.ʃəl",ko:"오늘의 요리, 특별한"},
  "speed": {ipa:"spiːd",ko:"속도를 내다"},
  "spell": {ipa:"spɛl",ko:"철자를 말하다"},
  "spicy": {ipa:"ˈspaɪsi",ko:"매운"},
  "split": {ipa:"splɪt",ko:"나누다"},
  "spoke": {ipa:"spəʊk",ko:"말했다"},
  "spring": {ipa:"spɹɪŋ",ko:"봄"},
  "squeeze": {ipa:"skwiːz",ko:"비집고 지나가다"},
  "stand": {ipa:"stænd",ko:"서다"},
  "start": {ipa:"stɑːt",ko:"시작하다"},
  "started": {ipa:"ˈstɑːtɪd",ko:"시작했다"},
  "station": {ipa:"ˈsteɪʃən",ko:"역"},
  "stay": {ipa:"steɪ",ko:"머물다, 유지하다"},
  "staying": {ipa:"ˈsteɪ.ɪŋ",ko:"머무는"},
  "stays": {ipa:"steɪz",ko:"머물다"},
  "stead": {ipa:"stɛd",ko:"대신"},
  "steady": {ipa:"ˈstɛdi",ko:"흔들리지 않게"},
  "step": {ipa:"stɛp",ko:"발을 옮기다"},
  "stifling": {ipa:"ˈstaɪflɪŋ",ko:"숨 막히는"},
  "stop": {ipa:"stɒp",ko:"정류장, 멈추다"},
  "stopover": {ipa:"ˈstɒpoʊvə",ko:"경유"},
  "stops": {ipa:"stɑps",ko:"정거장"},
  "storage": {ipa:"ˈstɔ.ɹɪd͡ʒ",ko:"보관"},
  "store": {ipa:"stɔː",ko:"가게, 보관하다"},
  "straight": {ipa:"stɹeɪt",ko:"곧장"},
  "strange": {ipa:"ˈstɹeɪnd͡ʒ",ko:"이상한"},
  "street": {ipa:"stɹiːt",ko:"거리"},
  "stretch": {ipa:"stɹɛtʃ",ko:"무리"},
  "stuffy": {ipa:"ˈstʌfi",ko:"공기가 탁한"},
  "subway": {ipa:"ˈsʌbˌweɪ",ko:"지하철"},
  "suggest": {ipa:"səˈdʒɛst",ko:"제안하다"},
  "suitcase": {ipa:"ˈsuːtkeɪs",ko:"여행 가방"},
  "sure": {ipa:"ʃʊə",ko:"확실한"},
  "surprised": {ipa:"səˈpɹaɪzd",ko:"놀란"},
  "swamped": {ipa:"swɒmpt",ko:"일이 밀린"},
  "swapping": {ipa:"ˈswɒpɪŋ",ko:"맞바꾸는"},
  "switch": {ipa:"swɪtʃ",ko:"바꾸다"},
  "switching": {ipa:"ˈswɪtʃɪŋ",ko:"바꾸는"},
  "table": {ipa:"ˈteɪbəl",ko:"자리, 탁자"},
  "tables": {ipa:"ˈteɪbl̩z",ko:"자리"},
  "tag": {ipa:"teɪɡ",ko:"꼬리표"},
  "take": {ipa:"teɪk",ko:"가져가다, 걸리다"},
  "takeaway": {ipa:"ˈteɪkəweɪ",ko:"포장"},
  "taken": {ipa:"ˈteɪkən",ko:"자리가 찬"},
  "takeoff": {ipa:"ˈteɪkɒf",ko:"이륙"},
  "taking": {ipa:"ˈteɪkɪŋ",ko:"찍는, 가져가는"},
  "talked": {ipa:"tɔːkt",ko:"이야기했다"},
  "tap": {ipa:"tæp",ko:"카드를 대다"},
  "tax": {ipa:"tæks",ko:"세금"},
  "taxi": {ipa:"ˈtæk.si",ko:"택시"},
  "tea": {ipa:"tiː",ko:"차"},
  "teach": {ipa:"tiːt͡ʃ",ko:"가르치다"},
  "tell": {ipa:"tɛl",ko:"말하다"},
  "terrible": {ipa:"ˈtɛ.ɹə.bl̩",ko:"끔찍한"},
  "terrified": {ipa:"ˈtɛɹɪfaɪd",ko:"몹시 두려운"},
  "than": {ipa:"ðæn"},
  "thanks": {ipa:"θæŋks",ko:"고맙습니다"},
  "that": {ipa:"ˈðæt"},
  "that's": {ipa:"ðæts"},
  "the": {ipa:"ðə"},
  "there": {ipa:"ðeə"},
  "there's": {ipa:"ðeəz"},
  "these": {ipa:"ðiːz"},
  "thing": {ipa:"θɪŋ",ko:"것"},
  "think": {ipa:"θɪŋk",ko:"생각하다"},
  "this": {ipa:"ðɪs"},
  "thought": {ipa:"θɔːt",ko:"생각했다"},
  "three": {ipa:"θɹiː"},
  "through": {ipa:"θɹuː"},
  "ticket": {ipa:"ˈtɪkɪt",ko:"표"},
  "tidy": {ipa:"ˈtaɪdi",ko:"정돈하다"},
  "tight": {ipa:"taɪt",ko:"꽉 끼는"},
  "time": {ipa:"taɪm",ko:"시간"},
  "tip": {ipa:"tɪp",ko:"팁"},
  "to": {ipa:"tuː"},
  "to-go": {ipa:"tə ˈɡoʊ",ko:"포장용"},
  "today": {ipa:"təˈdeɪ",ko:"오늘"},
  "today's": {ipa:"təˈdeɪz"},
  "together": {ipa:"təˈɡɛð.ə(ɹ)",ko:"함께"},
  "togo": {ipa:"tə ˈɡoʊ",ko:"포장용"},
  "toilet": {ipa:"ˈtɔɪ.lət",ko:"변기"},
  "too": {ipa:"tuː"},
  "totally": {ipa:"ˈtoʊt.əl.i",ko:"완전히"},
  "touch": {ipa:"tʌtʃ",ko:"연락, 만지다"},
  "touched": {ipa:"tʌt͡ʃt",ko:"감동한"},
  "tougher": {ipa:"ˈtʌfə",ko:"더 힘든"},
  "towels": {ipa:"ˈtaʊəlz",ko:"수건"},
  "trading": {ipa:"ˈtreɪdɪŋ",ko:"맞바꾸는"},
  "traffic": {ipa:"ˈtɹæfɪk",ko:"교통, 차량 흐름"},
  "train": {ipa:"tɹeɪn",ko:"기차"},
  "transfer": {ipa:"ˈtɹænzfɜː",ko:"환승하다"},
  "transit": {ipa:"ˈtɹæn.sɪt",ko:"환승"},
  "trash": {ipa:"tɹæʃ",ko:"쓰레기"},
  "trip": {ipa:"tɹɪp",ko:"여행"},
  "trolley": {ipa:"ˈtrɒli",ko:"짐 수레"},
  "trouble": {ipa:"ˈtɹʌb(ə)l",ko:"번거로움"},
  "troubling": {ipa:"ˈtɹʌb(ə)lɪŋ",ko:"성가시게 하는"},
  "try": {ipa:"tɹaɪ",ko:"해보다"},
  "trying": {ipa:"ˈtɹaɪ.ɪŋ",ko:"애쓰는"},
  "turbulence": {ipa:"ˈtɜːbjələns",ko:"난기류"},
  "turn": {ipa:"tɜːn",ko:"돌다, 켜다"},
  "turning": {ipa:"ˈtɜːnɪŋ",ko:"켜지는"},
  "tv": {ipa:"ˌtiːˈviː",ko:"티브이"},
  "two": {ipa:"tuː"},
  "umbrella": {ipa:"ʌmˈbrelə",ko:"우산"},
  "under": {ipa:"ˈʌndə"},
  "underground": {ipa:"ˈʌndəɡɹaʊnd",ko:"지하철"},
  "understand": {ipa:"ˌʌndəˈstænd",ko:"이해하다"},
  "unfair": {ipa:"ʌnˈfɛə(ɹ)",ko:"불공평한"},
  "unpredictable": {ipa:"ˌʌnprɪˈdɪktəbl",ko:"종잡을 수 없는"},
  "until": {ipa:"ənˈtɪl",ko:"~까지"},
  "up": {ipa:"ʌp"},
  "upgrade": {ipa:"ˈʌp.ɡɹeɪd",ko:"등급을 올리다"},
  "upright": {ipa:"ˈʌpɹaɪt",ko:"똑바로 세운"},
  "upset": {ipa:"ʌpˈset",ko:"속상한"},
  "upstairs": {ipa:"ˈʌpˌstɛəz",ko:"위층으로"},
  "us": {ipa:"əs"},
  "use": {ipa:"juːz",ko:"쓰다"},
  "usual": {ipa:"ˈjuːʒʊəl",ko:"평소"},
  "vacant": {ipa:"ˈveɪkənt",ko:"비어 있는"},
  "vacation": {ipa:"veɪˈkeɪʃ(ə)n",ko:"휴가"},
  "vegan": {ipa:"ˈviːɡən",ko:"완전 채식의"},
  "vegetarian": {ipa:"vɛd͡ʒɪˈtɛəɹi.ən",ko:"채식주의자"},
  "verify": {ipa:"ˈverɪfaɪ",ko:"확인하다"},
  "very": {ipa:"ˈvɛɹi"},
  "view": {ipa:"vjuː",ko:"전망"},
  "visit": {ipa:"ˈvɪzɪt",ko:"방문"},
  "visiting": {ipa:"ˈvɪzɪtɪŋ",ko:"방문하는"},
  "volume": {ipa:"ˈvɒl.juːm",ko:"음량"},
  "voucher": {ipa:"ˈvaʊtʃə(ɹ)",ko:"교환권"},
  "wait": {ipa:"weɪt",ko:"기다리다, 대기"},
  "waiting": {ipa:"ˈweɪtɪŋ",ko:"기다리는"},
  "wake-up": {ipa:"ˈweɪk ʌp",ko:"모닝콜의"},
  "wakeup": {ipa:"ˈweɪk ʌp",ko:"모닝콜의"},
  "walking": {ipa:"ˈwɔːkɪŋ",ko:"걷는"},
  "warm": {ipa:"wɔːm",ko:"따뜻한"},
  "was": {ipa:"wɒz"},
  "water": {ipa:"ˈwɔːtə",ko:"물"},
  "way": {ipa:"weɪ",ko:"길, 방식"},
  "we": {ipa:"wiː"},
  "we'd": {ipa:"wiːd"},
  "we'll": {ipa:"wiːl"},
  "we're": {ipa:"wɪə"},
  "weak": {ipa:"wiːk",ko:"약한"},
  "weather": {ipa:"ˈwɛðə",ko:"날씨"},
  "weather's": {ipa:"ˈweðəz"},
  "wedding": {ipa:"ˈwɛdɪŋ",ko:"결혼식"},
  "week": {ipa:"wiːk",ko:"주"},
  "weekend": {ipa:"wiːˈkɛnd",ko:"주말"},
  "weight": {ipa:"weɪt",ko:"무게"},
  "welcome": {ipa:"ˈwɛlkəm",ko:"천만에요"},
  "well": {ipa:"wɛl",ko:"잘"},
  "what": {ipa:"wɒt"},
  "what's": {ipa:"wɒts"},
  "when": {ipa:"ʍɛn"},
  "whenever": {ipa:"wəˈnɛvə",ko:"언제든"},
  "where": {ipa:"wɛə(ɹ)"},
  "where's": {ipa:"weəz"},
  "which": {ipa:"wɪt͡ʃ"},
  "while": {ipa:"waɪl"},
  "wi-fi": {ipa:"ˈwaɪfaɪ",ko:"와이파이"},
  "will": {ipa:"wɪl"},
  "window": {ipa:"ˈwɪndəʊ",ko:"창문, 창가"},
  "wishes": {ipa:"ˈwɪʃɪz",ko:"기원"},
  "with": {ipa:"wɪð"},
  "within": {ipa:"wɪˈθɪn",ko:"~이내에"},
  "won't": {ipa:"wəʊnt"},
  "wonderful": {ipa:"ˈwʌn.də.fl",ko:"훌륭한"},
  "word": {ipa:"wɜːd",ko:"말, 단어"},
  "words": {ipa:"wɜːdz",ko:"말"},
  "work": {ipa:"wɜːk",ko:"작동하다, 일하다"},
  "worked": {ipa:"wɜːkt",ko:"잘 풀렸다"},
  "working": {ipa:"ˈwɜːkɪŋ",ko:"작동하는"},
  "works": {ipa:"wɜːks",ko:"괜찮다, 작동하다"},
  "worn": {ipa:"wɔːn",ko:"지친"},
  "worry": {ipa:"ˈwɒɹi",ko:"걱정하다"},
  "worth": {ipa:"wɜːθ",ko:"~할 가치가 있는"},
  "would": {ipa:"wʊd"},
  "wrap": {ipa:"ɹæp",ko:"포장하다"},
  "write": {ipa:"ɹaɪt",ko:"쓰다"},
  "wrong": {ipa:"ɹɒŋ",ko:"잘못된"},
  "yet": {ipa:"jɛt"},
  "you": {ipa:"juː"},
  "you're": {ipa:"jɔː"},
  "your": {ipa:"jɔː"}
};
